#!/usr/bin/env python3
# This file is part of MiNap Go
# build.py
# Author(s): Gabriel Mongefranco
# Created: 2026-08-18
# Last Modified: 2026-08-18
# Summary: Packages src/ into gas/ (what a researcher pastes into an Apps Script project) and
#   app/ (what the site serves). Python standard library only -- no Node, no package manager,
#   nothing that talks to Google. Run with --check to verify the committed gas/ and app/ trees
#   still match what src/ produces, without writing anything.
# Notes: See README file for documentation and full license information.
#
# Copyright © 2026 The Regents of the University of Michigan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / 'src'
GAS_DIR = ROOT / 'gas'
APP_DIR = ROOT / 'app'

DEFAULT_AUTHOR = 'Gabriel Mongefranco'

LICENSE_BODY = [
    'This program is free software: you can redistribute it and/or modify',
    'it under the terms of the GNU General Public License as published by',
    'the Free Software Foundation, either version 3 of the License, or (at your option) any later version.',
    'This program is distributed in the hope that it will be useful,',
    'but WITHOUT ANY WARRANTY; without even the implied warranty of',
    'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the',
    'GNU General Public License for more details.',
    'You should have received a copy of the GNU General Public License along',
    'with this program. If not, see <https://www.gnu.org/licenses/>.',
]


def read(path):
    return path.read_text(encoding='utf-8')


### Header handling ###
# Every src/ file already carries its own AGENTS.md §3 header. Generated files reuse that
# header's content rather than inventing new dates or authors: 1:1 outputs (build_copy) keep
# the source header's own lines verbatim, just re-wrapped in the target comment style; merged
# outputs (build_merged) take Author/Created/Last Modified from their first constituent file
# and get a Summary written for the merged file itself.

def strip_header(text, style):
    """Splits a source file into (header content lines, body). Header content lines have
    their comment delimiters removed, one entry per line, in original order."""
    raw = text.splitlines(keepends=True)
    if style == 'js':
        i = 0
        while i < len(raw) and raw[i].startswith('//'):
            i += 1
        content = [l.rstrip('\n')[3:] if l.startswith('// ') else l.rstrip('\n')[2:] for l in raw[:i]]
        body = ''.join(raw[i:]).lstrip('\n')
        return content, body
    end_marker = '-->' if style == 'html' else '*/'
    for i, l in enumerate(raw):
        if l.strip() == end_marker:
            content = [l.rstrip('\n') for l in raw[1:i]]  # drop opening delimiter line and closing marker
            body = ''.join(raw[i + 1:]).lstrip('\n')
            return content, body
    raise ValueError('no header found (style=%s)' % style)


def render_header_lines(content_lines, style):
    """Re-wraps header content lines in the given comment style."""
    if style == 'js':
        return '\n'.join(('// ' + l).rstrip() if l else '//' for l in content_lines) + '\n'
    open_c = '<!--' if style == 'html' else '/*'
    close_c = '-->' if style == 'html' else '*/'
    return open_c + '\n' + '\n'.join(content_lines) + '\n' + close_c + '\n'


def insert_generated_note(content_lines, source_desc):
    """Adds the required 'generated, do not edit' line right after the Notes: line."""
    note = 'Generated by build.py from %s. Do not edit directly; edit the source and rerun build.py.' % source_desc
    out = list(content_lines)
    for i, l in enumerate(out):
        if l.startswith('Notes:'):
            out.insert(i + 1, note)
            return out
    out.append(note)
    return out


def field(text, label):
    """Pulls a single-line header field's value out of raw source text (Author(s)/Created/
    Last Modified are always single-line in this project; Summary may wrap and is handled
    separately per output, since a merged file needs its own Summary regardless)."""
    m = re.search(r'^(?://\s?)?' + re.escape(label) + r':\s*(.*)$', text, re.MULTILINE)
    return m.group(1).strip() if m else ''


def synth_header(style, filename, summary, author, created, modified, source_desc):
    """Builds a fresh header for a file with no single 1:1 source (a merge, or sw.js)."""
    content = [
        'This file is part of MiNap Go',
        filename,
        'Author(s): ' + author,
        'Created: ' + created,
        'Last Modified: ' + modified,
        'Summary: ' + summary,
        'Notes: See README file for documentation and full license information.',
    ]
    content = insert_generated_note(content, source_desc)
    content += [''] + ['Copyright © 2026 The Regents of the University of Michigan', ''] + LICENSE_BODY
    return render_header_lines(content, style)


### Per-file build steps ###

def build_copy(src_path, src_style, out_style, out_filename, source_desc, wrap=None):
    """1:1 output: reuse the source's own header (converted to out_style, generated-note
    added), and optionally wrap the body in an HTML tag pair (e.g. <style>/<script>)."""
    text = read(src_path)
    content, body = strip_header(text, src_style)
    if out_filename != content[1]:
        content = list(content)
        content[1] = out_filename
    content = insert_generated_note(content, source_desc)
    header = render_header_lines(content, out_style)
    if wrap:
        body = '<%s>\n%s</%s>\n' % (wrap, body, wrap)
    elif out_style == 'js':
        # Plain .js/.gs outputs keep one blank line between header and code, matching the
        # existing Code.gs convention; HTML-wrapped outputs (a <style>/<script> tag follows
        # immediately) do not.
        body = '\n' + body
    return header + body


def build_merged(src_paths, src_style, header_style, out_filename, summary, source_desc, wrap=None):
    """N:1 output: Author/Created/Last Modified come from the first file in src_paths
    (dependency order); Summary describes the merged file itself. src_style is the comment
    style of the constituent source files (always 'js' here); header_style is the comment
    style the *output* file needs (html when wrap='script' produces an .html file, js for a
    bare .js output) -- these differ for the gas/ targets, so they're kept as separate params."""
    first_text = read(src_paths[0])
    author = field(first_text, 'Author(s)') or DEFAULT_AUTHOR
    created = field(first_text, 'Created')
    modified = field(first_text, 'Last Modified') or created
    header = synth_header(header_style, out_filename, summary, author, created, modified, source_desc)
    parts = []
    for p in src_paths:
        _, body = strip_header(read(p), src_style)
        parts.append(body.rstrip('\n') + '\n')
    merged_body = '\n'.join(parts)
    if wrap:
        merged_body = '<%s>\n%s</%s>\n' % (wrap, merged_body, wrap)
    elif header_style == 'js':
        merged_body = '\n' + merged_body
    return header + merged_body


def license_sibling(src_path, source_desc):
    return read(src_path).rstrip('\n') + '\n\nGenerated by build.py from %s. Do not edit directly; ' \
        'edit the source and rerun build.py.\n' % source_desc


### Targets ###

def core_sources():
    # data/ first, then logic/, alphabetical within each -- the one-way dependency order
    # in architecture.md §16.2 (storage before rules).
    return sorted((SRC / 'data').glob('*.js')) + sorted((SRC / 'logic').glob('*.js'))


def ui_sources():
    return sorted((SRC / 'ui').glob('*.js'))


def build_gas():
    out = {}

    shell_body_subs = {
        "<!-- build:stylesheet -->": "<?!= include_('Stylesheet'); ?>",
        "<!-- build:scripts -->":
            "<?!= include_('Platform'); ?>\n  <?!= include_('Core'); ?>\n  <?!= include_('App'); ?>",
    }
    index_text = read(SRC / 'index.html')
    content, body = strip_header(index_text, 'html')
    content = insert_generated_note(content, 'src/index.html')
    for k, v in shell_body_subs.items():
        body = body.replace(k, v)
    out['Index.html'] = render_header_lines(content, 'html') + body

    out['Stylesheet.html'] = build_copy(SRC / 'styles.css', 'css', 'html', 'Stylesheet.html',
                                         'src/styles.css', wrap='style')
    out['Platform.html'] = build_copy(SRC / 'platform' / 'gas.js', 'js', 'html', 'Platform.html',
                                       'src/platform/gas.js', wrap='script')
    out['Core.html'] = build_merged(core_sources(), 'js', 'html', 'Core.html',
                                     'Storage and domain-rule logic for the MiNap Go client, '
                                     'merged from src/data/ and src/logic/.',
                                     'src/data/, src/logic/', wrap='script')
    out['App.html'] = build_merged(ui_sources(), 'js', 'html', 'App.html',
                                    'Screen rendering, DOM wiring, and startup for the MiNap Go '
                                    'client, merged from src/ui/.',
                                    'src/ui/', wrap='script')

    out['Code.gs'] = build_copy(SRC / 'server' / 'Code.gs', 'js', 'js', 'Code.gs',
                                 'src/server/Code.gs')

    out['appsscript.json'] = read(SRC / 'appsscript.json')
    out['appsscript.json.LICENSE.txt'] = license_sibling(
        SRC / 'appsscript.json.LICENSE.txt', 'src/appsscript.json.LICENSE.txt')

    return out


def build_app():
    out = {}

    out['index.html'] = build_copy(SRC / 'index.placeholder.html', 'html', 'html', 'index.html',
                                    'src/index.placeholder.html')
    out['styles.css'] = build_copy(SRC / 'styles.css', 'css', 'css', 'styles.css', 'src/styles.css')
    out['platform.js'] = build_copy(SRC / 'platform' / 'app.js', 'js', 'js', 'platform.js',
                                     'src/platform/app.js')
    out['core.js'] = build_merged(core_sources(), 'js', 'js', 'core.js',
                                   'Storage and domain-rule logic for the MiNap Go client, '
                                   'merged from src/data/ and src/logic/.',
                                   'src/data/, src/logic/')
    out['app.js'] = build_merged(ui_sources(), 'js', 'js', 'app.js',
                                  'Screen rendering, DOM wiring, and startup for the MiNap Go '
                                  'client, merged from src/ui/.',
                                  'src/ui/')

    # manifest.json carries its own notice in a leading "_license" key. The Web App Manifest
    # specification tells browsers to ignore members they do not recognise, so the key is
    # harmless. appsscript.json cannot do the same: Apps Script validates that file against a
    # fixed schema and rejects keys it does not know, so its notice stays in a sibling file.
    out['manifest.json'] = read(SRC / 'manifest.json')

    out['sw.js'] = build_service_worker(sorted(out.keys()))

    return out


SW_AUTHOR = 'Gabriel Mongefranco'
SW_CREATED = '2026-08-18'
SW_MODIFIED = '2026-08-18'


def build_service_worker(app_file_names):
    # app_file_names isn't used yet. It's threaded through now so a hash-based cache name and
    # a precache list can be derived from the actual packaged app/ files later, without
    # changing this function's signature (architecture.md §16.3).
    # TODO: add install/activate caching once the standalone build is wired to install at all.
    header = synth_header(
        'js', 'sw.js',
        'Service worker placeholder for the standalone build. Not registered by app/index.html yet.',
        SW_AUTHOR, SW_CREATED, SW_MODIFIED,
        "build_service_worker() in build.py (no single src/ file backs this one)")
    body = (
        "// Intentionally inert: no caching logic, and nothing in app/ registers this worker\n"
        "// yet. Kept as its own file because a service worker's scope is fixed to the URL\n"
        "// it is served from, so it cannot be merged with another script.\n"
    )
    return header + body


### Write / check ###

def write_all(target_dir, files):
    for name, content in files.items():
        path = target_dir / name
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(content)


def check(target_dir, files):
    ok = True
    on_disk = {}
    if target_dir.exists():
        for p in target_dir.rglob('*'):
            if p.is_file():
                on_disk[str(p.relative_to(target_dir)).replace('\\', '/')] = read(p)
    expected = {k.replace('\\', '/'): v for k, v in files.items()}
    for name in sorted(set(expected) | set(on_disk)):
        if name not in on_disk:
            print('MISSING on disk: %s/%s' % (target_dir.name, name))
            ok = False
        elif name not in expected:
            print('EXTRA on disk (not produced by build.py): %s/%s' % (target_dir.name, name))
            ok = False
        elif on_disk[name] != expected[name]:
            print('MISMATCH: %s/%s' % (target_dir.name, name))
            ok = False
    return ok


def main():
    gas_files = build_gas()
    app_files = build_app()

    if '--check' in sys.argv:
        ok_gas = check(GAS_DIR, gas_files)
        ok_app = check(APP_DIR, app_files)
        if ok_gas and ok_app:
            print('OK: gas/ and app/ match src/.')
            sys.exit(0)
        sys.exit(1)

    write_all(GAS_DIR, gas_files)
    write_all(APP_DIR, app_files)
    print('Wrote %d files to gas/, %d files to app/.' % (len(gas_files), len(app_files)))


if __name__ == '__main__':
    main()
