// This file is part of MiNap Go
// app.js
// Author(s): Gabriel Mongefranco
// Created: 2026-08-18
// Last Modified: 2026-08-18
// Summary: Screen rendering, DOM wiring, and startup for the MiNap Go client, merged from src/ui/.
// Notes: See README file for documentation and full license information.
// Generated by build.py from src/ui/. Do not edit directly; edit the source and rerun build.py.
//
// Copyright © 2026 The Regents of the University of Michigan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along
// with this program. If not, see <https://www.gnu.org/licenses/>.

var MSG_INVALID_CREDENTIALS = 'Please contact the study to ensure the Study ID and Participant ID are correct.';
var MSG_LOGIN_FAILED = 'Unable to log in. Please verify the Study ID and Participant ID are correct.';
var MSG_LOGIN_UNREACHABLE = 'Unable to reach the study server right now. Check your connection and try again.';

function setLoginBusy(busy) {
  document.getElementById('btn-start').disabled = busy;
  document.getElementById('btn-start-label').classList.toggle('hidden', busy);
  document.getElementById('btn-start-spinner').classList.toggle('hidden', !busy);
}

function doStart() {
  var study = document.getElementById('in-study').value.trim().toUpperCase();
  var part = document.getElementById('in-part').value.trim().toUpperCase();
  var tz = document.getElementById('in-tz').value;
  if (!study || !part) { toast('Enter Study ID and Participant ID'); return; }

  setLoginBusy(true);
  validateLogin(study, part, function (res) {
    setLoginBusy(false);
    if (!res || !res.valid) { toast(MSG_LOGIN_FAILED); return; }
    save(K_SESSION, { study_id: study, participant_id: part, tz: tz, created_at: new Date().toISOString() });
    enterHome();
  }, function () {
    setLoginBusy(false);
    toast(MSG_LOGIN_UNREACHABLE);
  });
}

function enterHome() {
  var session = load(K_SESSION, null);
  document.getElementById('who-study').textContent = session.study_id;
  document.getElementById('who-part').textContent = session.participant_id;
  show('screen-home');
  applyHomeState();   // from cache first (instant)
  flushQueue();
  checkRevocation(true); // catches a revoked ID, then re-applies state
}

// Clears the local session and returns to login. `message`, if given, is toasted
// (used when the server rejects a revoked Study/Participant ID); the manual
// "Log out" link calls this with no message.
function forceLogout(message) {
  clearAll();
  showOverlay(false);
  document.getElementById('in-study').value = '';
  document.getElementById('in-part').value = '';
  show('screen-login');
  if (message) toast(message);
}

function doLogout() {
  forceLogout();
}

// The server has the final say on the allowlist: if this participant's ID was
// revoked, don't keep showing (possibly stale) local history — log out immediately.
function checkRevocation(thenApplyHome) {
  var session = load(K_SESSION, null);
  if (!session) return;
  validateLogin(session.study_id, session.participant_id, function (res) {
    if (!res || !res.valid) { forceLogout(MSG_INVALID_CREDENTIALS); return; }
    if (thenApplyHome) applyHomeState();
  }, function () {}); // request never completed (offline/etc.) - stay logged in, retry later
}

function loadConfig() {
  getConfig(function (cfg) { if (cfg && cfg.editWindowDays) editWindowDays = cfg.editWindowDays; }, function () {});
}

function boot() {
  buildTzOptions();
  loadConfig();
  document.getElementById('btn-start').addEventListener('click', doStart);
  document.getElementById('btn-logout').addEventListener('click', doLogout);
  document.getElementById('btn-sleep').addEventListener('click', onSleep);
  document.getElementById('btn-wake').addEventListener('click', onWake);
  document.getElementById('btn-history').addEventListener('click', function () {
    renderHistory();
    showOverlay(false);
    show('screen-history');
    checkRevocation(false); // catches a revoked ID
  });
  document.getElementById('btn-back').addEventListener('click', function () { show('screen-home'); applyHomeState(); });
  document.getElementById('history-list').addEventListener('click', function (e) {
    var btn = e.target.closest('.edit-time');
    if (btn) openEditor(btn.getAttribute('data-id'));
  });
  document.getElementById('btn-edit-cancel').addEventListener('click', closeEditor);
  document.getElementById('btn-edit-save').addEventListener('click', saveEditor);

  if (load(K_SESSION, null)) enterHome();
  else show('screen-login');
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
else boot();

function pairNights(events) {
  var asc = events.slice().sort(function (a, b) { return a.event_epoch_ms - b.event_epoch_ms; });
  var nights = [];
  var openSleep = null;
  asc.forEach(function (e) {
    if (e.event_type === 'SLEEP') {
      if (openSleep) nights.push({ sleep: openSleep, wake: null });
      openSleep = e;
    } else {
      nights.push({ sleep: openSleep, wake: e });
      openSleep = null;
    }
  });
  if (openSleep) nights.push({ sleep: openSleep, wake: null });
  return nights.reverse();
}

function timeField(ev, label) {
  var text = label + ' ' + fmtTime(ev);
  if (!ev) return text;
  var edited = ev.edited === 'TRUE' || ev.edited === true;
  if (edited) text += '<sup>*</sup>';
  var extra = '';
  if (isEditable(ev)) {
    extra = ' <button type="button" class="edit-time' + (edited ? ' edited' : '') + '" data-id="' + ev.record_id + '" ' +
      'aria-label="Edit ' + label.toLowerCase() + ' time">&#9998;</button>';
  }
  return text + extra;
}

function renderHistory() {
  var box = document.getElementById('history-list');
  var hist = load(K_HISTORY, []);
  if (!hist.length) {
    box.innerHTML = '<div class="empty"><div class="moon">&#127769;</div><p>No nights yet. Tap Go to sleep to begin.</p></div>';
    return;
  }
  var nights = pairNights(hist);
  box.innerHTML = nights.map(function (n) {
    var anchor = n.sleep || n.wake;
    var pill;
    if (n.sleep && n.wake) {
      var auto = n.wake.auto ? ' auto' : '';
      var lbl = n.wake.auto ? 'auto ' : '';
      pill = '<span class="pill' + auto + '">' + lbl + fmtDur(n.wake.event_epoch_ms - n.sleep.event_epoch_ms) + '</span>';
    } else {
      pill = '<span class="pill open">' + (n.sleep ? 'in progress' : 'wake only') + '</span>';
    }
    return '' +
      '<div class="night">' +
        '<div>' +
          '<div class="date">' + fmtDate(anchor) + '</div>' +
          '<div class="times">' + timeField(n.sleep, 'Sleep') + ' &middot; ' + timeField(n.wake, 'Wake') + '</div>' +
        '</div>' + pill +
      '</div>';
  }).join('');
}

// ----- editing a previous entry's date/time -----
function findHistEvent(recordId) {
  var hist = load(K_HISTORY, []);
  for (var i = 0; i < hist.length; i++) {
    if (hist[i].record_id === recordId) return hist[i];
  }
  return null;
}

var editingRecordId = null;

function openEditor(recordId) {
  var ev = findHistEvent(recordId);
  if (!ev || !isEditable(ev)) return;
  editingRecordId = recordId;
  document.getElementById('edit-modal-title').textContent =
    'Edit ' + (ev.event_type === 'SLEEP' ? 'sleep' : 'wake') + ' time';
  document.getElementById('edit-datetime').value = toDatetimeLocalValue(ev.event_epoch_ms, ev.event_tz);
  document.getElementById('edit-modal').classList.remove('hidden');
}

function closeEditor() {
  editingRecordId = null;
  document.getElementById('edit-modal').classList.add('hidden');
}

function applyServerUpdate(saved) {
  if (!saved) return;
  var hist = load(K_HISTORY, []);
  for (var i = 0; i < hist.length; i++) {
    if (hist[i].record_id === saved.record_id) { hist[i] = saved; break; }
  }
  save(K_HISTORY, hist);
}

function saveEditor() {
  var ev = findHistEvent(editingRecordId);
  var session = load(K_SESSION, null);
  if (!ev || !session) { closeEditor(); return; }

  var val = document.getElementById('edit-datetime').value; // "YYYY-MM-DDTHH:mm"
  var m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/.exec(val || '');
  if (!m) { toast('Enter a valid date and time'); return; }

  var epoch = epochFromWallTime(Number(m[1]), Number(m[2]), Number(m[3]), Number(m[4]), Number(m[5]), ev.event_tz);
  var d = new Date(epoch);
  var updated = {
    record_id: ev.record_id,
    study_id: session.study_id,
    participant_id: session.participant_id,
    event_epoch_ms: epoch,
    event_iso_utc: d.toISOString(),
    event_tz: ev.event_tz,
    event_local: d.toLocaleString('en-US', { timeZone: ev.event_tz, hour12: true })
  };

  // Show the edit immediately (same optimistic-first pattern as logging a new event);
  // the server round-trip below reconciles with the authoritative row afterward.
  applyServerUpdate(Object.assign({}, ev, updated, { edited: 'TRUE' }));
  closeEditor();
  renderHistory();

  var btn = document.getElementById('btn-edit-save');
  btn.disabled = true;
  updateEvent(updated, function (res) {
    btn.disabled = false;
    if (res && res.invalid) { toast(MSG_INVALID_CREDENTIALS); return; }
    applyServerUpdate(res && res.row);
    renderHistory();
    toast('Time updated');
  }, function () {
    btn.disabled = false;
    toast('Could not save. Try again.');
  });
}

function show(id) {
  ['screen-login', 'screen-home', 'screen-history'].forEach(function (s) {
    document.getElementById(s).classList.toggle('hidden', s !== id);
  });
}
function showOverlay(on) {
  document.getElementById('sleep-overlay').classList.toggle('hidden', !on);
}

var toastTimer = null;
function toast(msg) {
  var t = document.getElementById('toast');
  t.textContent = msg;
  t.classList.remove('hidden');
  clearTimeout(toastTimer);
  toastTimer = setTimeout(function () { t.classList.add('hidden'); }, 2200);
}

// Best-effort local timezone via Intl; falls back to a sane default if unavailable.
function detectTz() {
  try { return Intl.DateTimeFormat().resolvedOptions().timeZone || 'America/Detroit'; }
  catch (e) { return 'America/Detroit'; }
}
// Populate the timezone dropdown, defaulting to the browser-detected zone.
function buildTzOptions() {
  var sel = document.getElementById('in-tz');
  var auto = detectTz();
  var zones = [
    'America/New_York', 'America/Detroit', 'America/Chicago', 'America/Denver',
    'America/Phoenix', 'America/Los_Angeles', 'America/Anchorage', 'Pacific/Honolulu',
    'America/Toronto', 'Europe/London', 'UTC'
  ];
  if (zones.indexOf(auto) === -1) zones.unshift(auto);
  sel.innerHTML = '';
  zones.forEach(function (z) {
    var o = document.createElement('option');
    o.value = z;
    o.textContent = (z === auto) ? (z + ' (detected)') : z;
    if (z === auto) o.selected = true;
    sel.appendChild(o);
  });
}

var AUTO_WAKE_HOURS = 12; // auto-wake if asleep for more than this many hours

// Sleeping if the most recent event is a SLEEP with no WAKE after it.
function computeState() {
  var hist = load(K_HISTORY, []);
  if (!hist.length) return 'AWAKE';
  return hist[0].event_type === 'SLEEP' ? 'SLEEPING' : 'AWAKE';
}

// The open SLEEP event, if the user is currently asleep.
function topSleep() {
  var hist = load(K_HISTORY, []);
  return (hist.length && hist[0].event_type === 'SLEEP') ? hist[0] : null;
}

// If asleep for >= AUTO_WAKE_HOURS, auto-log a wake on app open.
function maybeAutoWake() {
  var sleep = topSleep();
  if (!sleep) return false;
  var session = load(K_SESSION, null);
  if (!session) return false;
  var hours = (Date.now() - Number(sleep.event_epoch_ms)) / 3600000;
  if (hours < AUTO_WAKE_HOURS) return false;
  var ev = buildEvent('WAKE', session);
  ev.auto = true; // local display flag only
  recordEvent(ev);
  toast('Auto-logged wake (12h elapsed)');
  return true;
}

function applyHomeState() {
  maybeAutoWake();
  var st = computeState();
  if (st === 'SLEEPING') {
    var s = topSleep();
    var label = fmtClock(s.event_epoch_ms, s.event_tz);
    if (!sameDay(s.event_epoch_ms, s.event_tz)) {
      label = new Date(s.event_epoch_ms)
        .toLocaleDateString('en-US', { timeZone: s.event_tz, weekday: 'short' }) + ' ' + label;
    }
    document.getElementById('asleep-since').textContent = 'Since ' + label;
    showOverlay(true);
  } else {
    showOverlay(false);
  }
  renderStatus();
}

function renderStatus() {
  var chip = document.getElementById('status-chip');
  chip.textContent = computeState() === 'SLEEPING' ? 'Are you ready to wake up?' : 'Are you going to sleep?';
}

function onSleep() {
  var session = load(K_SESSION, null);
  if (!session) { show('screen-login'); return; }
  recordEvent(buildEvent('SLEEP', session));
  toast('Sleep logged ' + fmtClock(Date.now(), session.tz));
  applyHomeState();
}

function onWake() {
  var session = load(K_SESSION, null);
  if (!session) { show('screen-login'); return; }
  recordEvent(buildEvent('WAKE', session));
  toast('Good morning. Wake logged ' + fmtClock(Date.now(), session.tz));
  applyHomeState();
}

// Drain the offline queue one item at a time; a failure halts the drain until the next call.
function flushQueue() {
  var q = load(K_QUEUE, []);
  if (!q.length) return;
  var next = q.shift();
  save(K_QUEUE, q);
  sendEvent(next, function (ok, res) {
    if (ok && res && res.invalid) {
      toast(MSG_INVALID_CREDENTIALS); // will never succeed until re-validated; don't requeue
      return;
    }
    if (!ok) {
      var qq = load(K_QUEUE, []); qq.push(res); save(K_QUEUE, qq);
    } else {
      flushQueue();
    }
  });
}

// append locally + push to server (with offline retry queue)
function recordEvent(ev) {
  var hist = load(K_HISTORY, []);
  hist.unshift(ev);
  save(K_HISTORY, hist);
  sendEvent(ev, function (ok, res) {
    if (ok && res && res.invalid) {
      toast(MSG_INVALID_CREDENTIALS);
      return;
    }
    if (!ok) {
      var q = load(K_QUEUE, []); q.push(ev); save(K_QUEUE, q);
    }
  });
}
