// This file is part of MiNap Go
// app.js
// Author(s): Gabriel Mongefranco
// Created: 2026-08-18
// Last Modified: 2026-08-19
// Summary: Screen rendering, DOM wiring, and startup for the MiNap Go client, merged from src/ui/.
// Notes: See README file for documentation and full license information.
// Generated by build.py from src/ui/. Do not edit directly; edit the source and rerun build.py.
//
// Copyright © 2026 The Regents of the University of Michigan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along
// with this program. If not, see <https://www.gnu.org/licenses/>.

// Mirrors Code.gs's PIN_MIN_LENGTH, for instant feedback on the setup/change screens. The
// server re-checks this itself and stays authoritative -- this constant only saves a round trip
// on the common case of typing too few digits.
var PIN_MIN_LENGTH = 6;

// One reason -> message lookup, shared by every screen that can receive a {ok, reason} or
// {valid, reason} envelope, so a reason is never translated into user-facing text more than
// once and nothing ever branches on err.message from a google.script.run failure handler.
var REASON_MESSAGES = {
  invalid_login: 'Please contact the study to ensure the Study ID and Participant ID are correct.',
  locked: 'Too many incorrect attempts. Contact your study team to unlock your account.',
  wrong_pin: 'Incorrect PIN. Try again.',
  pin_too_short: 'Choose a PIN of at least ' + PIN_MIN_LENGTH + ' digits.',
  not_set: 'No PIN is on file yet for this participant.',
  offline: 'You need a connection to do this. Check your connection and try again.'
};

var MSG_LOGIN_FAILED = 'Unable to log in. Please verify the Study ID and Participant ID are correct.';
var MSG_LOGIN_UNREACHABLE = 'Unable to reach the study server right now. Check your connection and try again.';

// The identity a PIN-setup or PIN-entry screen is currently acting on, and which of the three
// ways it got there: 'local-unlock' (a profile already exists on this device -- fully offline),
// 'server-verify' (a PIN is already set server-side, but this device has no local profile yet),
// or set implicitly by beginPinSetup (no PIN exists anywhere yet).
var pendingIdentity = null;
var pendingMode = null;

function setButtonBusy(id, busy) {
  document.getElementById(id).disabled = busy;
  document.getElementById(id + '-label').classList.toggle('hidden', busy);
  document.getElementById(id + '-spinner').classList.toggle('hidden', !busy);
}
function setLoginBusy(busy) { setButtonBusy('btn-start', busy); }
function setPinEntryBusy(busy) { setButtonBusy('btn-pin-entry', busy); }
function setPinSetupBusy(busy) { setButtonBusy('btn-pin-setup', busy); }
function setChangePinBusy(busy) { setButtonBusy('btn-change-pin-save', busy); }

function showPinEntryError(msg) { document.getElementById('pin-entry-error').textContent = msg; }
function showPinSetupError(msg) { document.getElementById('pin-setup-error').textContent = msg; }
function showChangePinError(msg) { document.getElementById('change-pin-error').textContent = msg; }

// Study/Participant ID submitted: routes to PIN entry (local unlock, or a server verify if this
// is a new device) or PIN setup (nobody has chosen a PIN for this identity yet), depending on
// what this device already knows and what the server says.
async function doStart() {
  var study = document.getElementById('in-study').value.trim().toUpperCase();
  var part = document.getElementById('in-part').value.trim().toUpperCase();
  var tz = document.getElementById('in-tz').value;
  if (!study || !part) { toast('Enter Study ID and Participant ID'); return; }

  setLoginBusy(true);
  var profile = await getProfile(study, part);
  if (profile) {
    setLoginBusy(false);
    beginPinEntry(study, part, tz, 'local-unlock');
    return;
  }

  validateLogin(study, part, function (res) {
    setLoginBusy(false);
    if (!res || !res.valid) { toast(MSG_LOGIN_FAILED); return; }
    if (res.pinSet) beginPinEntry(study, part, tz, 'server-verify');
    else beginPinSetup(study, part, tz);
  }, function () {
    setLoginBusy(false);
    toast(MSG_LOGIN_UNREACHABLE);
  });
}

function doSwitchAccount() {
  document.getElementById('in-study').value = '';
  document.getElementById('in-part').value = '';
  clearLastIdentity();
  document.getElementById('in-study').focus();
}

function beginPinEntry(studyId, participantId, tz, mode) {
  pendingIdentity = { studyId: studyId, participantId: participantId, tz: tz };
  pendingMode = mode;
  showPinEntryError('');
  document.getElementById('in-pin-entry').value = '';
  show('screen-pin-entry');
  document.getElementById('in-pin-entry').focus();
}

function beginPinSetup(studyId, participantId, tz) {
  pendingIdentity = { studyId: studyId, participantId: participantId, tz: tz };
  pendingMode = 'setup';
  showPinSetupError('');
  document.getElementById('in-pin-new').value = '';
  document.getElementById('in-pin-confirm').value = '';
  show('screen-pin-setup');
  document.getElementById('in-pin-new').focus();
}

function backToLogin() {
  pendingIdentity = null;
  pendingMode = null;
  show('screen-login');
}

// PIN entered on the entry screen: unwraps locally (fully offline, when a profile already
// exists on this device) or checks it against the server and bootstraps a fresh local profile
// (a device seeing this identity for the first time has nothing to unwrap yet -- there is no
// read path to repopulate its history from, so it legitimately starts empty).
async function doPinEntry() {
  var pin = document.getElementById('in-pin-entry').value;
  if (!pin) { toast('Enter your PIN'); return; }
  var id = pendingIdentity;
  setPinEntryBusy(true);

  if (pendingMode === 'local-unlock') {
    var ok = await unlockWithPin(id.studyId, id.participantId, pin);
    setPinEntryBusy(false);
    if (!ok) { showPinEntryError(REASON_MESSAGES.wrong_pin); return; }
    await setLastIdentity(id.studyId, id.participantId);
    enterHome(); // revalidates in the background itself; local unlock already let them in
    return;
  }

  verifyPin(id.studyId, id.participantId, pin, function (res) {
    if (!res || !res.ok) {
      setPinEntryBusy(false);
      showPinEntryError(REASON_MESSAGES[res && res.reason] || MSG_LOGIN_FAILED);
      return;
    }
    createLocalProfile(id.studyId, id.participantId, id.tz, pin)
      .then(function () { return setLastIdentity(id.studyId, id.participantId); })
      .then(function () {
        setPinEntryBusy(false);
        enterHome();
      });
  }, function () {
    setPinEntryBusy(false);
    toast(MSG_LOGIN_UNREACHABLE);
  });
}

// PIN chosen on the setup screen: registers it server-side first, then mints the local key --
// in that order, so a device never holds a local profile the server doesn't also know about.
function doPinSetup() {
  var pin = document.getElementById('in-pin-new').value;
  var confirmPin = document.getElementById('in-pin-confirm').value;
  if (!pin || pin.length < PIN_MIN_LENGTH) { showPinSetupError(REASON_MESSAGES.pin_too_short); return; }
  if (pin !== confirmPin) { showPinSetupError('PINs do not match.'); return; }

  var id = pendingIdentity;
  setPinSetupBusy(true);
  setPin(id.studyId, id.participantId, pin, undefined, function (res) {
    if (!res || !res.ok) {
      setPinSetupBusy(false);
      showPinSetupError(REASON_MESSAGES[res && res.reason] || 'Could not set PIN. Try again.');
      return;
    }
    createLocalProfile(id.studyId, id.participantId, id.tz, pin)
      .then(function () { return setLastIdentity(id.studyId, id.participantId); })
      .then(function () {
        setPinSetupBusy(false);
        enterHome();
      });
  }, function () {
    setPinSetupBusy(false);
    toast(MSG_LOGIN_UNREACHABLE);
  });
}

async function enterHome() {
  var identity = getSessionIdentity();
  document.getElementById('who-study').textContent = identity.studyId;
  document.getElementById('who-part').textContent = identity.participantId;
  show('screen-home');
  await applyHomeState(); // from cache first (instant)
  flushQueue();
  checkRevocation(true); // catches a revoked ID, then re-applies state
}

// Ends the session without touching local data: a participant who logs back in with the
// correct PIN sees the same history, unchanged. Returns to PIN entry for the same identity,
// since nothing about it was forgotten. See docs/architecture.md's local storage section.
function doLogout() {
  var identity = getSessionIdentity();
  lock();
  showOverlay(false);
  if (identity) beginPinEntry(identity.studyId, identity.participantId, null, 'local-unlock');
  else show('screen-login');
}

// The server has the final say on the allowlist: if this participant's ID was revoked, stop
// them continuing on (possibly stale) local history. This also only locks, never deletes --
// a later re-enable should not cost the participant their on-device history.
function forceLogout(message) {
  lock();
  showOverlay(false);
  show('screen-login');
  if (message) toast(message);
}

function checkRevocation(thenApplyHome) {
  var identity = getSessionIdentity();
  if (!identity) return;
  validateLogin(identity.studyId, identity.participantId, function (res) {
    if (!res || !res.valid) { forceLogout(REASON_MESSAGES.invalid_login); return; }
    if (thenApplyHome) applyHomeState();
  }, function () {}); // request never completed (offline/etc.) - stay logged in, retry later
}

// ----- Change PIN: a distinct case from setup or forgot-it (architecture.md section 5.2) -----

function openChangePinModal() {
  showChangePinError('');
  document.getElementById('in-pin-old').value = '';
  document.getElementById('in-pin-change-new').value = '';
  document.getElementById('in-pin-change-confirm').value = '';
  openModal('change-pin-modal');
  document.getElementById('in-pin-old').focus();
}
function closeChangePinModal() {
  closeModal('change-pin-modal');
}

async function doChangePin() {
  var oldPin = document.getElementById('in-pin-old').value;
  var newPin = document.getElementById('in-pin-change-new').value;
  var confirmPin = document.getElementById('in-pin-change-confirm').value;
  if (!newPin || newPin.length < PIN_MIN_LENGTH) { showChangePinError(REASON_MESSAGES.pin_too_short); return; }
  if (newPin !== confirmPin) { showChangePinError('New PINs do not match.'); return; }

  setChangePinBusy(true);
  var result = await changePin(oldPin, newPin);
  setChangePinBusy(false);
  if (!result.ok) { showChangePinError(REASON_MESSAGES[result.reason] || 'Could not change PIN. Try again.'); return; }
  closeChangePinModal();
  toast('PIN changed');
}

function loadConfig() {
  getConfig(function (cfg) { if (cfg && cfg.editWindowDays) editWindowDays = cfg.editWindowDays; }, function () {});
}

async function boot() {
  buildTzOptions();
  loadConfig();

  document.getElementById('btn-start').addEventListener('click', doStart);
  document.getElementById('btn-switch-account').addEventListener('click', doSwitchAccount);
  document.getElementById('btn-pin-entry').addEventListener('click', doPinEntry);
  document.getElementById('btn-pin-entry-back').addEventListener('click', backToLogin);
  document.getElementById('btn-pin-setup').addEventListener('click', doPinSetup);
  document.getElementById('btn-pin-setup-back').addEventListener('click', backToLogin);
  document.getElementById('btn-logout').addEventListener('click', doLogout);
  document.getElementById('btn-change-pin').addEventListener('click', openChangePinModal);
  document.getElementById('btn-change-pin-cancel').addEventListener('click', closeChangePinModal);
  document.getElementById('btn-change-pin-save').addEventListener('click', doChangePin);
  document.getElementById('btn-sleep').addEventListener('click', onSleep);
  document.getElementById('btn-wake').addEventListener('click', onWake);
  document.getElementById('btn-history').addEventListener('click', function () {
    renderHistory();
    showOverlay(false);
    show('screen-history');
    checkRevocation(false); // catches a revoked ID
  });
  document.getElementById('btn-back').addEventListener('click', function () { show('screen-home'); applyHomeState(); });
  document.getElementById('history-list').addEventListener('click', function (e) {
    var btn = e.target.closest('.edit-time');
    if (btn) openEditor(btn.getAttribute('data-id'));
  });
  document.getElementById('btn-edit-cancel').addEventListener('click', closeEditor);
  document.getElementById('btn-edit-save').addEventListener('click', saveEditor);

  var last = await getLastIdentity();
  if (last) {
    document.getElementById('in-study').value = last.study_id;
    document.getElementById('in-part').value = last.participant_id;
  }
  show('screen-login');
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
else boot();

function pairNights(events) {
  var asc = events.slice().sort(function (a, b) { return a.event_epoch_ms - b.event_epoch_ms; });
  var nights = [];
  var openSleep = null;
  asc.forEach(function (e) {
    if (e.event_type === 'SLEEP') {
      if (openSleep) nights.push({ sleep: openSleep, wake: null });
      openSleep = e;
    } else {
      nights.push({ sleep: openSleep, wake: e });
      openSleep = null;
    }
  });
  if (openSleep) nights.push({ sleep: openSleep, wake: null });
  return nights.reverse();
}

function timeField(ev, label) {
  var text = label + ' ' + fmtTime(ev);
  if (!ev) return text;
  var edited = ev.edited === 'TRUE' || ev.edited === true;
  if (edited) text += '<sup>*</sup>';
  var extra = '';
  if (isEditable(ev)) {
    extra = ' <button type="button" class="edit-time' + (edited ? ' edited' : '') + '" data-id="' + ev.record_id + '" ' +
      'aria-label="Edit ' + label.toLowerCase() + ' time">&#9998;</button>';
  }
  return text + extra;
}

async function renderHistory() {
  var box = document.getElementById('history-list');
  var hist = await getHistory();
  if (!hist.length) {
    box.innerHTML = '<div class="empty"><div class="moon">&#127769;</div><p>No nights yet. Tap Go to sleep to begin.</p></div>';
    return;
  }
  var nights = pairNights(hist);
  box.innerHTML = nights.map(function (n) {
    var anchor = n.sleep || n.wake;
    var pill;
    if (n.sleep && n.wake) {
      var auto = n.wake.auto ? ' auto' : '';
      var lbl = n.wake.auto ? 'auto ' : '';
      pill = '<span class="pill' + auto + '">' + lbl + fmtDur(n.wake.event_epoch_ms - n.sleep.event_epoch_ms) + '</span>';
    } else {
      pill = '<span class="pill open">' + (n.sleep ? 'in progress' : 'wake only') + '</span>';
    }
    return '' +
      '<div class="night">' +
        '<div>' +
          '<div class="date">' + fmtDate(anchor) + '</div>' +
          '<div class="times">' + timeField(n.sleep, 'Sleep') + ' &middot; ' + timeField(n.wake, 'Wake') + '</div>' +
        '</div>' + pill +
      '</div>';
  }).join('');
}

// ----- editing a previous entry's date/time -----
async function findHistEvent(recordId) {
  var hist = await getHistory();
  for (var i = 0; i < hist.length; i++) {
    if (hist[i].record_id === recordId) return hist[i];
  }
  return null;
}

var editingRecordId = null;

async function openEditor(recordId) {
  var ev = await findHistEvent(recordId);
  if (!ev || !isEditable(ev)) return;
  editingRecordId = recordId;
  document.getElementById('edit-modal-title').textContent =
    'Edit ' + (ev.event_type === 'SLEEP' ? 'sleep' : 'wake') + ' time';
  document.getElementById('edit-datetime').value = toDatetimeLocalValue(ev.event_epoch_ms, ev.event_tz);
  openModal('edit-modal');
}

function closeEditor() {
  editingRecordId = null;
  closeModal('edit-modal');
}

async function applyServerUpdate(saved) {
  if (!saved) return;
  await updateHistory(function (hist) {
    for (var i = 0; i < hist.length; i++) {
      if (hist[i].record_id === saved.record_id) { hist[i] = saved; break; }
    }
    return hist;
  });
}

async function saveEditor() {
  var ev = await findHistEvent(editingRecordId);
  var identity = getSessionIdentity();
  if (!ev || !identity) { closeEditor(); return; }

  var val = document.getElementById('edit-datetime').value; // "YYYY-MM-DDTHH:mm"
  var m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/.exec(val || '');
  if (!m) { toast('Enter a valid date and time'); return; }

  var epoch = epochFromWallTime(Number(m[1]), Number(m[2]), Number(m[3]), Number(m[4]), Number(m[5]), ev.event_tz);
  var d = new Date(epoch);
  var updated = {
    record_id: ev.record_id,
    study_id: identity.studyId,
    participant_id: identity.participantId,
    event_epoch_ms: epoch,
    event_iso_utc: d.toISOString(),
    event_tz: ev.event_tz,
    event_local: d.toLocaleString('en-US', { timeZone: ev.event_tz, hour12: true })
  };

  // Show the edit immediately (same optimistic-first pattern as logging a new event);
  // the server round-trip below reconciles with the authoritative row afterward.
  await applyServerUpdate(Object.assign({}, ev, updated, { edited: 'TRUE' }));
  closeEditor();
  renderHistory();

  var btn = document.getElementById('btn-edit-save');
  btn.disabled = true;
  updateEvent(updated, function (res) {
    btn.disabled = false;
    if (res && res.invalid) { toast(REASON_MESSAGES.invalid_login); return; }
    applyServerUpdate(res && res.row);
    renderHistory();
    toast('Time updated');
  }, function () {
    btn.disabled = false;
    toast('Could not save. Try again.');
  });
}

// Iterates every element carrying the .screen class rather than a hardcoded id list, so a new
// screen only has to be marked up with that class to participate -- nothing here has to change.
function show(id) {
  document.querySelectorAll('.screen').forEach(function (s) {
    s.classList.toggle('hidden', s.id !== id);
  });
}
function showOverlay(on) {
  document.getElementById('sleep-overlay').classList.toggle('hidden', !on);
}

// Shows/hides one of the modal dialogs. Focus-trap and focus-restore land in Stage 3; every
// dialog in the app is meant to route through these two functions so that work only has to be
// written once.
function openModal(id) {
  document.getElementById(id).classList.remove('hidden');
}
function closeModal(id) {
  document.getElementById(id).classList.add('hidden');
}

var toastTimer = null;
function toast(msg) {
  var t = document.getElementById('toast');
  t.textContent = msg;
  t.classList.remove('hidden');
  clearTimeout(toastTimer);
  toastTimer = setTimeout(function () { t.classList.add('hidden'); }, 2200);
}

// Best-effort local timezone via Intl; falls back to a sane default if unavailable.
function detectTz() {
  try { return Intl.DateTimeFormat().resolvedOptions().timeZone || 'America/Detroit'; }
  catch (e) { return 'America/Detroit'; }
}
// Populate the timezone dropdown, defaulting to the browser-detected zone.
function buildTzOptions() {
  var sel = document.getElementById('in-tz');
  var auto = detectTz();
  var zones = [
    'America/New_York', 'America/Detroit', 'America/Chicago', 'America/Denver',
    'America/Phoenix', 'America/Los_Angeles', 'America/Anchorage', 'Pacific/Honolulu',
    'America/Toronto', 'Europe/London', 'UTC'
  ];
  if (zones.indexOf(auto) === -1) zones.unshift(auto);
  sel.innerHTML = '';
  zones.forEach(function (z) {
    var o = document.createElement('option');
    o.value = z;
    o.textContent = (z === auto) ? (z + ' (detected)') : z;
    if (z === auto) o.selected = true;
    sel.appendChild(o);
  });
}

var AUTO_WAKE_HOURS = 12; // auto-wake if asleep for more than this many hours

// buildEvent expects study_id/participant_id/tz; the vault's session identity uses
// studyId/participantId/tz. This is the one adapter point between the two shapes.
function sessionForBuildEvent(identity) {
  return { study_id: identity.studyId, participant_id: identity.participantId, tz: identity.tz };
}

// Sleeping if the most recent event is a SLEEP with no WAKE after it.
async function computeState() {
  var hist = await getHistory();
  if (!hist.length) return 'AWAKE';
  return hist[0].event_type === 'SLEEP' ? 'SLEEPING' : 'AWAKE';
}

// The open SLEEP event, if the user is currently asleep.
async function topSleep() {
  var hist = await getHistory();
  return (hist.length && hist[0].event_type === 'SLEEP') ? hist[0] : null;
}

// If asleep for >= AUTO_WAKE_HOURS, auto-log a wake on app open.
async function maybeAutoWake() {
  var sleep = await topSleep();
  if (!sleep) return false;
  var identity = getSessionIdentity();
  if (!identity) return false;
  var hours = (Date.now() - Number(sleep.event_epoch_ms)) / 3600000;
  if (hours < AUTO_WAKE_HOURS) return false;
  var ev = buildEvent('WAKE', sessionForBuildEvent(identity));
  ev.auto = true; // local display flag only
  await recordEvent(ev);
  toast('Auto-logged wake (12h elapsed)');
  return true;
}

async function applyHomeState() {
  await maybeAutoWake();
  var st = await computeState();
  if (st === 'SLEEPING') {
    var s = await topSleep();
    var label = fmtClock(s.event_epoch_ms, s.event_tz);
    if (!sameDay(s.event_epoch_ms, s.event_tz)) {
      label = new Date(s.event_epoch_ms)
        .toLocaleDateString('en-US', { timeZone: s.event_tz, weekday: 'short' }) + ' ' + label;
    }
    document.getElementById('asleep-since').textContent = 'Since ' + label;
    showOverlay(true);
  } else {
    showOverlay(false);
  }
  await renderStatus();
}

async function renderStatus() {
  var chip = document.getElementById('status-chip');
  chip.textContent = (await computeState()) === 'SLEEPING' ? 'Are you ready to wake up?' : 'Are you going to sleep?';
}

async function onSleep() {
  var identity = getSessionIdentity();
  if (!identity) { show('screen-login'); return; }
  await recordEvent(buildEvent('SLEEP', sessionForBuildEvent(identity)));
  toast('Sleep logged ' + fmtClock(Date.now(), identity.tz));
  applyHomeState();
}

async function onWake() {
  var identity = getSessionIdentity();
  if (!identity) { show('screen-login'); return; }
  await recordEvent(buildEvent('WAKE', sessionForBuildEvent(identity)));
  toast('Good morning. Wake logged ' + fmtClock(Date.now(), identity.tz));
  applyHomeState();
}

// Drain the offline queue one item at a time; a failure halts the drain until the next call.
// The real drain engine (idempotent dispatch by kind, never-retry-on-revoke) is Stage 3 -- this
// keeps today's shape, only made async, so the app keeps running end to end in the meantime.
async function flushQueue() {
  var q = await getQueue();
  if (!q.length) return;
  var next = q.shift();
  await setQueue(q);
  sendEvent(next, function (ok, res) {
    if (ok && res && res.invalid) {
      toast(REASON_MESSAGES.invalid_login); // will never succeed until re-validated; don't requeue
      return;
    }
    if (!ok) {
      updateQueue(function (qq) { qq.push(res); return qq; });
    } else {
      flushQueue();
    }
  });
}

// append locally + push to server (with offline retry queue)
async function recordEvent(ev) {
  await updateHistory(function (hist) { hist.unshift(ev); return hist; });
  sendEvent(ev, function (ok, res) {
    if (ok && res && res.invalid) {
      toast(REASON_MESSAGES.invalid_login);
      return;
    }
    if (!ok) {
      updateQueue(function (q) { q.push(ev); return q; });
    }
  });
}
