// This file is part of MiNap Go
// app.js
// Author(s): Gabriel Mongefranco
// Created: 2026-08-18
// Last Modified: 2026-08-19
// Summary: Screen rendering, DOM wiring, and startup for the MiNap Go client, merged from src/ui/.
// Notes: See README file for documentation and full license information.
// Generated by build.py from src/ui/. Do not edit directly; edit the source and rerun build.py.
//
// Copyright © 2026 The Regents of the University of Michigan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along
// with this program. If not, see <https://www.gnu.org/licenses/>.

// Mirrors Code.gs's PIN_MIN_LENGTH, for instant feedback on the setup/change screens. The
// server re-checks this itself and stays authoritative -- this constant only saves a round trip
// on the common case of typing too few digits.
var PIN_MIN_LENGTH = 6;

// How long a device may go without a successful checkSession before the interface says so.
// Nothing here ever signs anyone out for being offline -- see checkRevocation below -- this only
// controls when the quiet "not checked recently" line appears. Matches the fifteen-day backup
// reminder closely enough to be one interval a person has to remember.
var SESSION_REVALIDATE_DAYS = 14;

// One reason -> message lookup, shared by every screen that can receive a {ok, reason} or
// {valid, reason} envelope, so a reason is never translated into user-facing text more than
// once and nothing ever branches on err.message from a google.script.run failure handler.
var REASON_MESSAGES = {
  invalid_login: 'Please contact the study to ensure the Study ID and Participant ID are correct.',
  locked: 'Too many incorrect attempts. Contact your study team to unlock your account.',
  wrong_pin: 'Incorrect PIN. Try again.',
  pin_too_short: 'Choose a PIN of at least ' + PIN_MIN_LENGTH + ' digits.',
  not_set: 'No PIN is on file yet for this participant.',
  device_not_recognized: 'Please enter your PIN again on this device.',
  offline: 'You need a connection to do this. Check your connection and try again.',
  already_answered: 'This diary was already completed.',
  edit_window_expired: 'This is too old to edit or complete now.',
  not_found: 'That entry could not be found. It may have been removed.',
  busy: 'The study server is busy right now. This will be sent automatically shortly.',
  invalid_payload: 'This entry could not be sent. Please contact your study team.'
};

var MSG_LOGIN_FAILED = 'Unable to log in. Please verify the Study ID and Participant ID are correct.';
var MSG_LOGIN_UNREACHABLE = 'Unable to reach the study server right now. Check your connection and try again.';

// The identity a PIN-setup or PIN-entry screen is currently acting on, and which of the three
// ways it got there: 'local-unlock' (a profile already exists on this device, so a verified PIN
// unwraps it), 'server-verify' (a PIN is already set server-side, but this device has no local
// profile yet), or set implicitly by beginPinSetup (no PIN exists anywhere yet). Both PIN-entry
// modes confirm the PIN with the server before doing anything else: unwrapping a local profile
// is offline-capable on its own, but a device token can only be minted server-side, and signing
// in without one would leave the app unable to write anything.
var pendingIdentity = null;
var pendingMode = null;

function setButtonBusy(id, busy) {
  document.getElementById(id).disabled = busy;
  document.getElementById(id + '-label').classList.toggle('hidden', busy);
  document.getElementById(id + '-spinner').classList.toggle('hidden', !busy);
}
function setLoginBusy(busy) { setButtonBusy('btn-start', busy); }
function setPinEntryBusy(busy) { setButtonBusy('btn-pin-entry', busy); }
function setPinSetupBusy(busy) { setButtonBusy('btn-pin-setup', busy); }
function setChangePinBusy(busy) { setButtonBusy('btn-change-pin-save', busy); }

function showPinEntryError(msg) { document.getElementById('pin-entry-error').textContent = msg; }
function showPinSetupError(msg) { document.getElementById('pin-setup-error').textContent = msg; }
function showChangePinError(msg) { document.getElementById('change-pin-error').textContent = msg; }

// Study/Participant ID submitted: routes to PIN entry (this device already has a local profile
// to unwrap, or does not) or PIN setup (nobody has chosen a PIN for this identity yet),
// depending on what this device already knows and what the server says. Only reached after
// boot()'s tryAutoResume has already failed for the last identity used on this device, so a
// profile existing locally here does not by itself mean the device is still signed in.
async function doStart() {
  var study = document.getElementById('in-study').value.trim().toUpperCase();
  var part = document.getElementById('in-part').value.trim().toUpperCase();
  var tz = document.getElementById('in-tz').value;
  if (!study || !part) { toast('Enter Study ID and Participant ID'); return; }

  setLoginBusy(true);
  var profile = await getProfile(study, part);
  if (profile) {
    setLoginBusy(false);
    beginPinEntry(study, part, tz, 'local-unlock');
    return;
  }

  validateLogin(study, part, function (res) {
    setLoginBusy(false);
    if (!res || !res.valid) { toast(MSG_LOGIN_FAILED); return; }
    if (res.pinSet) beginPinEntry(study, part, tz, 'server-verify');
    else beginPinSetup(study, part, tz);
  }, function () {
    setLoginBusy(false);
    toast(MSG_LOGIN_UNREACHABLE);
  });
}

function doSwitchAccount() {
  document.getElementById('in-study').value = '';
  document.getElementById('in-part').value = '';
  clearLastIdentity();
  document.getElementById('in-study').focus();
}

function beginPinEntry(studyId, participantId, tz, mode) {
  pendingIdentity = { studyId: studyId, participantId: participantId, tz: tz };
  pendingMode = mode;
  showPinEntryError('');
  document.getElementById('in-pin-entry').value = '';
  show('screen-pin-entry');
  document.getElementById('in-pin-entry').focus();
}

function beginPinSetup(studyId, participantId, tz) {
  pendingIdentity = { studyId: studyId, participantId: participantId, tz: tz };
  pendingMode = 'setup';
  showPinSetupError('');
  document.getElementById('in-pin-new').value = '';
  document.getElementById('in-pin-confirm').value = '';
  show('screen-pin-setup');
  document.getElementById('in-pin-new').focus();
}

function backToLogin() {
  pendingIdentity = null;
  pendingMode = null;
  show('screen-login');
}

// PIN entered on the entry screen. Always confirms with the server first (verifyPin), whether
// or not this device already has a local profile to unwrap: unwrapping is local and works
// offline on its own, but only the server can mint the device token a fresh sign-in needs, so
// entering a PIN here requires connectivity either way. What 'local-unlock' still changes is
// only what happens after a successful verify -- unwrapping an existing profile rather than
// creating a new one.
async function doPinEntry() {
  var pin = document.getElementById('in-pin-entry').value;
  if (!pin) { toast('Enter your PIN'); return; }
  var id = pendingIdentity;
  var hasLocalProfile = pendingMode === 'local-unlock';
  setPinEntryBusy(true);

  verifyPin(id.studyId, id.participantId, pin, function (res) {
    if (!res || !res.ok) {
      setPinEntryBusy(false);
      showPinEntryError(REASON_MESSAGES[res && res.reason] || MSG_LOGIN_FAILED);
      return;
    }
    var established = hasLocalProfile
      ? unlockWithPin(id.studyId, id.participantId, pin, res.deviceToken)
      : createLocalProfile(id.studyId, id.participantId, id.tz, pin, res.deviceToken)
        .then(function () { return true; });

    established.then(function (unlockedOk) {
      setPinEntryBusy(false);
      if (hasLocalProfile && !unlockedOk) {
        // The server just accepted this PIN, but this device's own locally-wrapped copy did
        // not unwrap with it. Only reachable if the PIN was changed from a different device
        // after this one last signed in, which leaves this device's local copy permanently
        // under the old PIN -- there is no way to re-derive it from the new one. Not
        // auto-recovered: that would mean silently discarding an encrypted profile the
        // participant never asked to discard.
        showPinEntryError('This PIN does not match what is stored on this device. If you '
          + 'changed your PIN on another device, contact your study team about resetting this '
          + 'one.');
        return;
      }
      setLastIdentity(id.studyId, id.participantId).then(enterHome);
    });
  }, function () {
    setPinEntryBusy(false);
    toast(MSG_LOGIN_UNREACHABLE);
  });
}

// PIN chosen on the setup screen: registers it server-side first, then mints the local key --
// in that order, so a device never holds a local profile the server doesn't also know about.
function doPinSetup() {
  var pin = document.getElementById('in-pin-new').value;
  var confirmPin = document.getElementById('in-pin-confirm').value;
  if (!pin || pin.length < PIN_MIN_LENGTH) { showPinSetupError(REASON_MESSAGES.pin_too_short); return; }
  if (pin !== confirmPin) { showPinSetupError('PINs do not match.'); return; }

  var id = pendingIdentity;
  setPinSetupBusy(true);
  setPin(id.studyId, id.participantId, pin, undefined, function (res) {
    if (!res || !res.ok) {
      setPinSetupBusy(false);
      showPinSetupError(REASON_MESSAGES[res && res.reason] || 'Could not set PIN. Try again.');
      return;
    }
    createLocalProfile(id.studyId, id.participantId, id.tz, pin, res.deviceToken)
      .then(function () { return setLastIdentity(id.studyId, id.participantId); })
      .then(function () {
        setPinSetupBusy(false);
        enterHome();
      });
  }, function () {
    setPinSetupBusy(false);
    toast(MSG_LOGIN_UNREACHABLE);
  });
}

async function enterHome() {
  var identity = getSessionIdentity();
  document.getElementById('who-study').textContent = identity.studyId;
  document.getElementById('who-part').textContent = identity.participantId;
  show('screen-home');
  await applyHomeState(); // from cache first (instant)
  await updateSessionNote();
  flushQueue();
  checkRevocation(true); // confirms this device is still recognised, then re-applies state
}

// Shows or hides the quiet "have not checked in a while" line, per SESSION_REVALIDATE_DAYS.
// This is purely informational -- being offline never signs anyone out (checkRevocation) -- it
// only tells the participant their entries are queued rather than confirmed recently.
async function updateSessionNote() {
  var note = document.getElementById('session-note');
  var identity = getSessionIdentity();
  if (!identity) { note.classList.add('hidden'); return; }
  var profile = await getProfile(identity.studyId, identity.participantId);
  var lastVerified = profile && profile.last_verified_utc;
  var daysSince = lastVerified ? (Date.now() - new Date(lastVerified).getTime()) / 86400000 : Infinity;
  if (daysSince > SESSION_REVALIDATE_DAYS) {
    note.textContent = 'This device has not checked in with the study server in a while. '
      + 'Your entries are still saved here.';
    note.classList.remove('hidden');
  } else {
    note.classList.add('hidden');
  }
}

// Ends the session without touching local data: a participant who logs back in with the
// correct PIN sees the same history, unchanged. Returns to PIN entry for the same identity,
// since nothing about it was forgotten. See docs/architecture.md's local storage section.
async function doLogout() {
  var identity = getSessionIdentity();
  if (identity) await logout(identity.studyId, identity.participantId);
  showOverlay(false);
  if (identity) beginPinEntry(identity.studyId, identity.participantId, identity.tz, 'local-unlock');
  else show('screen-login');
}

// The server has the final say on the allowlist: if this participant's ID was revoked, stop
// them continuing on (possibly stale) local history. Routes through the same vault.logout as an
// explicit "Log out" -- not just clearing the in-memory session -- because the device key would
// otherwise still be sitting on disk, and the very next boot's tryAutoResume would use it to
// walk straight back into Home with no PIN prompt at all, undoing the point of logging out here.
// This still only locks, never deletes: a later re-enable should not cost the participant their
// on-device history.
function forceLogout(message) {
  var identity = getSessionIdentity();
  var cleanup = identity ? logout(identity.studyId, identity.participantId) : Promise.resolve();
  cleanup.then(function () {
    showOverlay(false);
    show('screen-login');
    if (message) toast(message);
  });
}

// A device whose token the server no longer recognises -- replaced by another device signing
// in, or cleared by the researcher -- keeps every queued and stored entry. Unlike forceLogout,
// nothing about this participant's access was actually revoked, so there is nothing to warn
// them out of; the queue simply cannot drain until the PIN is entered again to mint a fresh
// token. Clearing the local device-key material (via the same vault.logout used for an explicit
// logout) is what stops the next boot from silently auto-resuming with the token that was just
// rejected.
function softSignOut(message) {
  var identity = getSessionIdentity();
  if (!identity) return;
  logout(identity.studyId, identity.participantId).then(function () {
    showOverlay(false);
    beginPinEntry(identity.studyId, identity.participantId, identity.tz, 'local-unlock');
    if (message) toast(message);
  });
}

// Confirms this device is still the one recognised for this participant. Called on entering
// Home and History, per docs/architecture.md section 5.6: authoritative only on an explicit
// rejection from the server, never on a failure to reach it at all -- an offline participant is
// never signed out, they simply keep working and try again on the next trigger.
function checkRevocation(thenApplyHome) {
  var identity = getSessionIdentity();
  var token = getSessionToken();
  if (!identity || !token) return;
  checkSession(identity.studyId, identity.participantId, token, function (res) {
    if (res && res.ok) {
      markSessionVerified().then(updateSessionNote);
      if (thenApplyHome) applyHomeState();
      return;
    }
    if (res && res.reason === 'device_not_recognized') {
      softSignOut(REASON_MESSAGES.device_not_recognized);
      return;
    }
    forceLogout(REASON_MESSAGES[(res && res.reason) || 'invalid_login']);
  }, function () {}); // request never completed (offline/etc.) -- stay signed in, retry later
}

// ----- Change PIN: a distinct case from setup or forgot-it (architecture.md section 5.2) -----

function openChangePinModal() {
  showChangePinError('');
  document.getElementById('in-pin-old').value = '';
  document.getElementById('in-pin-change-new').value = '';
  document.getElementById('in-pin-change-confirm').value = '';
  openModal('change-pin-modal');
  document.getElementById('in-pin-old').focus();
}
function closeChangePinModal() {
  closeModal('change-pin-modal');
}

async function doChangePin() {
  var oldPin = document.getElementById('in-pin-old').value;
  var newPin = document.getElementById('in-pin-change-new').value;
  var confirmPin = document.getElementById('in-pin-change-confirm').value;
  if (!newPin || newPin.length < PIN_MIN_LENGTH) { showChangePinError(REASON_MESSAGES.pin_too_short); return; }
  if (newPin !== confirmPin) { showChangePinError('New PINs do not match.'); return; }

  setChangePinBusy(true);
  var result = await changePin(oldPin, newPin);
  setChangePinBusy(false);
  if (!result.ok) { showChangePinError(REASON_MESSAGES[result.reason] || 'Could not change PIN. Try again.'); return; }
  closeChangePinModal();
  toast('PIN changed');
}

function loadConfig() {
  getConfig(function (cfg) { if (cfg && cfg.editWindowDays) editWindowDays = cfg.editWindowDays; }, function () {});
}

async function boot() {
  buildTzOptions();
  loadConfig();

  document.getElementById('btn-start').addEventListener('click', doStart);
  document.getElementById('btn-switch-account').addEventListener('click', doSwitchAccount);
  document.getElementById('btn-pin-entry').addEventListener('click', doPinEntry);
  document.getElementById('btn-pin-entry-back').addEventListener('click', backToLogin);
  document.getElementById('btn-pin-setup').addEventListener('click', doPinSetup);
  document.getElementById('btn-pin-setup-back').addEventListener('click', backToLogin);
  document.getElementById('btn-logout').addEventListener('click', doLogout);
  document.getElementById('btn-change-pin').addEventListener('click', openChangePinModal);
  document.getElementById('btn-change-pin-cancel').addEventListener('click', closeChangePinModal);
  document.getElementById('btn-change-pin-save').addEventListener('click', doChangePin);
  document.getElementById('btn-sleep').addEventListener('click', onSleep);
  document.getElementById('btn-wake').addEventListener('click', onWake);
  document.getElementById('btn-history').addEventListener('click', function () {
    renderHistory();
    showOverlay(false);
    show('screen-history');
    checkRevocation(false); // catches a revoked ID
  });
  document.getElementById('btn-back').addEventListener('click', function () { show('screen-home'); applyHomeState(); });
  document.getElementById('history-list').addEventListener('click', function (e) {
    var editBtn = e.target.closest('.edit-time');
    if (editBtn) { openEditor(editBtn.getAttribute('data-id')); return; }
    var completeBtn = e.target.closest('.complete-survey');
    if (completeBtn) beginCompletion(completeBtn.getAttribute('data-sleep-day'));
  });
  document.getElementById('btn-edit-cancel').addEventListener('click', closeEditor);
  document.getElementById('btn-edit-save').addEventListener('click', saveEditor);

  document.getElementById('survey-questions').addEventListener('input', onSurveyInput);
  document.getElementById('survey-questions').addEventListener('change', onSurveyChange);
  document.getElementById('survey-questions').addEventListener('click', onSurveyStep);
  document.getElementById('btn-survey-submit').addEventListener('click', doSurveySubmit);
  document.getElementById('btn-survey-skip').addEventListener('click', doSurveySkip);
  document.getElementById('btn-survey-cancel').addEventListener('click', doSurveyCancel);

  // Retries whatever is still queued the moment connectivity returns, rather than waiting for
  // the participant to reopen the app or visit History. A no-op with no active session (nothing
  // queued can exist before someone has signed in on this device).
  window.addEventListener('online', function () {
    if (getSessionIdentity()) flushQueue();
  });

  var last = await getLastIdentity();
  if (last) {
    document.getElementById('in-study').value = last.study_id;
    document.getElementById('in-part').value = last.participant_id;
    // No PIN prompt, no network call: reads the device key this identity left behind (if any)
    // and unwraps straight into a working session. Falls through to the login screen, still
    // pre-filled, whenever there is nothing to resume.
    var resumed = await tryAutoResume(last.study_id, last.participant_id);
    if (resumed) { enterHome(); return; }
  }
  show('screen-login');
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
else boot();

var FOCUSABLE_SELECTOR = 'a[href], button:not([disabled]), textarea:not([disabled]), ' +
  'input:not([disabled]):not([type="hidden"]), select:not([disabled]), [tabindex]:not([tabindex="-1"])';

// One dialog at a time is all this app ever opens, so a single module-level record of what is
// trapped and what to return focus to is enough -- no stack needed.
var focusTrapState = null;

function visibleFocusable(container) {
  return Array.prototype.slice.call(container.querySelectorAll(FOCUSABLE_SELECTOR))
    .filter(function (el) { return el.offsetParent !== null; });
}

function trapKeydown(e) {
  if (e.key !== 'Tab' || !focusTrapState) return;
  var focusable = visibleFocusable(focusTrapState.container);
  if (!focusable.length) return;
  var first = focusable[0], last = focusable[focusable.length - 1];
  if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
  else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
}

// Marks container as the active dialog: sets aria-modal, remembers what had focus so it can be
// restored, moves focus inside, and starts trapping Tab/Shift+Tab within it. Safe to call again
// on the same container while it is already trapped -- the edit and change-PIN modals are
// re-opened rather than re-rendered while visible, so this mainly guards against a stray
// double call.
function trapFocus(container) {
  if (focusTrapState && focusTrapState.container === container) return;
  releaseFocus();
  container.setAttribute('aria-modal', 'true');
  container.addEventListener('keydown', trapKeydown);
  focusTrapState = { trigger: document.activeElement, container: container };
  var target = visibleFocusable(container)[0] || container;
  target.focus();
}

// Removes the trap and returns focus to whatever opened the dialog, if it is still in the page --
// a participant who closed a dialog that replaced its own trigger (rare in this app, but cheap
// to guard) simply keeps whatever focus the close action already set.
function releaseFocus() {
  if (!focusTrapState) return;
  focusTrapState.container.removeEventListener('keydown', trapKeydown);
  focusTrapState.container.removeAttribute('aria-modal');
  var trigger = focusTrapState.trigger;
  focusTrapState = null;
  if (trigger && document.body.contains(trigger) && typeof trigger.focus === 'function') {
    trigger.focus();
  }
}

// The night a pair of markers describes, for deciding whether a completion entry point applies
// and for matching it to a locally-known survey record. Mirrors assignSleepDay_ on the server:
// a SLEEP names its own night directly; a WAKE with no SLEEP on this device falls back to the
// noon rule on its own local time.
function nightSleepDay(hist, night) {
  if (night.sleep) return sleepDayFromLocal(night.sleep.event_local);
  if (night.wake) return findPrecedingSleepDayLocal(hist, night.wake.event_epoch_ms, night.wake.event_local);
  return null;
}

function timeField(ev, label, queuedIds) {
  var text = label + ' ' + fmtTime(ev);
  if (!ev) return text;
  if (ev.edited) text += '<sup>*</sup>';
  if (queuedIds && queuedIds[ev.record_id]) text += ' <span class="not-sent">Not yet sent</span>';
  var extra = '';
  if (isEditable(ev)) {
    extra = ' <button type="button" class="edit-time' + (ev.edited ? ' edited' : '') + '" data-id="' + ev.record_id + '" ' +
      'aria-label="Edit ' + label.toLowerCase() + ' time">&#9998;</button>';
  }
  return text + extra;
}

async function renderHistory() {
  var box = document.getElementById('history-list');
  var hist = await getHistory();
  if (!hist.length) {
    box.innerHTML = '<div class="empty"><div class="moon">&#127769;</div><p>No nights yet. Tap Go to sleep to begin.</p></div>';
    return;
  }
  var nights = pairNights(hist);
  var surveys = await getSurveys();
  var queuedIds = await queuedRecordIds();
  var queuedSurveys = await queuedSurveyIds();

  box.innerHTML = nights.map(function (n) {
    var anchor = n.sleep || n.wake;
    var pill;
    if (n.sleep && n.wake) {
      var auto = n.wake.auto ? ' auto' : '';
      var lbl = n.wake.auto ? 'auto ' : '';
      pill = '<span class="pill' + auto + '">' + lbl + fmtDur(n.wake.event_epoch_ms - n.sleep.event_epoch_ms) + '</span>';
    } else {
      pill = '<span class="pill open">' + (n.sleep ? 'in progress' : 'wake only') + '</span>';
    }

    var sleepDay = nightSleepDay(hist, n);
    var record = sleepDay ? surveys.filter(function (s) { return s.sleep_day === sleepDay; })[0] : null;
    var completion = '';
    if (n.wake && sleepDay && !isSurveyLocked(record) && isSleepDayCompletable(sleepDay)) {
      completion = '<button type="button" class="complete-survey" data-sleep-day="' + sleepDay + '">' +
        (record ? 'Finish diary' : 'Add diary') + '</button>';
    } else if (record && isSurveyLocked(record)) {
      completion = '<span class="survey-done">Diary ' + escapeHtml(record.end_reason) +
        (queuedSurveys[record.survey_id] ? ' &middot; <span class="not-sent">Not yet sent</span>' : '') +
        '</span>';
    }

    return '' +
      '<div class="night">' +
        '<div>' +
          '<div class="date">' + fmtDate(anchor) + '</div>' +
          '<div class="times">' + timeField(n.sleep, 'Sleep', queuedIds) + ' &middot; ' + timeField(n.wake, 'Wake', queuedIds) + '</div>' +
          completion +
        '</div>' + pill +
      '</div>';
  }).join('');
}

// ----- completing a skipped or missing survey from the history list -----

async function beginCompletion(sleepDay) {
  var hist = await getHistory();
  var nights = pairNights(hist);
  var match = nights.filter(function (n) { return nightSleepDay(hist, n) === sleepDay; })[0];
  if (!match) return;
  var surveys = await getSurveys();
  var existingRecord = surveys.filter(function (s) { return s.sleep_day === sleepDay; })[0] || null;
  openSurveyForCompletion({
    sleepDay: sleepDay, sleepEvent: match.sleep, wakeEvent: match.wake, existingRecord: existingRecord
  });
}

// ----- editing a previous entry's date/time -----
async function findHistEvent(recordId) {
  var hist = await getHistory();
  for (var i = 0; i < hist.length; i++) {
    if (hist[i].record_id === recordId) return hist[i];
  }
  return null;
}

var editingRecordId = null;

async function openEditor(recordId) {
  var ev = await findHistEvent(recordId);
  if (!ev || !isEditable(ev)) return;
  editingRecordId = recordId;
  document.getElementById('edit-modal-title').textContent =
    'Edit ' + (ev.marker === 'SLEEP' ? 'sleep' : 'wake') + ' time';
  document.getElementById('edit-datetime').value = toDatetimeLocalValue(ev.event_epoch_ms, ev.event_tz);
  openModal('edit-modal');
}

function closeEditor() {
  editingRecordId = null;
  closeModal('edit-modal');
}

async function applyLocalUpdate(updated) {
  if (!updated) return;
  await updateHistory(function (hist) {
    for (var i = 0; i < hist.length; i++) {
      if (hist[i].record_id === updated.record_id) { hist[i] = updated; break; }
    }
    return hist;
  });
}

async function saveEditor() {
  var ev = await findHistEvent(editingRecordId);
  if (!ev || !getSessionIdentity()) { closeEditor(); return; }

  var val = document.getElementById('edit-datetime').value; // "YYYY-MM-DDTHH:mm"
  var m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/.exec(val || '');
  if (!m) { toast('Enter a valid date and time'); return; }

  var epoch = epochFromWallTime(Number(m[1]), Number(m[2]), Number(m[3]), Number(m[4]), Number(m[5]), ev.event_tz);
  var clientEditUtc = new Date().toISOString();
  var updated = Object.assign({}, ev, {
    event_epoch_ms: epoch,
    event_utc: new Date(epoch).toISOString(),
    event_local: toLocalIsoWithOffset(epoch, ev.event_tz),
    edited: true
  });

  // Show the edit immediately, the same optimistic-first pattern recordEvent uses for a new
  // marker. The queued request below reconciles with the server's authoritative row once it
  // lands, whether that is now or after the app is next online.
  await applyLocalUpdate(updated);
  closeEditor();
  renderHistory();

  await enqueue('marker_edit', { event: updated, client_edit_utc: clientEditUtc });
  flushQueue();
  toast('Time updated. Sending…');
}

// Iterates every element carrying the .screen class rather than a hardcoded id list, so a new
// screen only has to be marked up with that class to participate -- nothing here has to change.
function show(id) {
  document.querySelectorAll('.screen').forEach(function (s) {
    s.classList.toggle('hidden', s.id !== id);
  });
}
function showOverlay(on) {
  var el = document.getElementById('sleep-overlay');
  el.classList.toggle('hidden', !on);
  if (on) trapFocus(el); else releaseFocus();
}

// Shows/hides one of the modal dialogs, trapping and restoring focus around it. Every dialog in
// the app routes through these two functions, so that work is written once rather than per
// dialog.
function openModal(id) {
  var el = document.getElementById(id);
  el.classList.remove('hidden');
  trapFocus(el);
}
function closeModal(id) {
  document.getElementById(id).classList.add('hidden');
  releaseFocus();
}

var toastTimer = null;
function toast(msg) {
  var t = document.getElementById('toast');
  t.textContent = msg;
  t.classList.remove('hidden');
  clearTimeout(toastTimer);
  toastTimer = setTimeout(function () { t.classList.add('hidden'); }, 2200);
}

// Best-effort local timezone via Intl; falls back to a sane default if unavailable.
function detectTz() {
  try { return Intl.DateTimeFormat().resolvedOptions().timeZone || 'America/Detroit'; }
  catch (e) { return 'America/Detroit'; }
}
// Populate the timezone dropdown, defaulting to the browser-detected zone.
function buildTzOptions() {
  var sel = document.getElementById('in-tz');
  var auto = detectTz();
  var zones = [
    'America/New_York', 'America/Detroit', 'America/Chicago', 'America/Denver',
    'America/Phoenix', 'America/Los_Angeles', 'America/Anchorage', 'Pacific/Honolulu',
    'America/Toronto', 'Europe/London', 'UTC'
  ];
  if (zones.indexOf(auto) === -1) zones.unshift(auto);
  sel.innerHTML = '';
  zones.forEach(function (z) {
    var o = document.createElement('option');
    o.value = z;
    o.textContent = (z === auto) ? (z + ' (detected)') : z;
    if (z === auto) o.selected = true;
    sel.appendChild(o);
  });
}

var AUTO_WAKE_HOURS = 12; // auto-wake if asleep for more than this many hours

// buildEvent expects study_id/participant_id/tz; the vault's session identity uses
// studyId/participantId/tz. This is the one adapter point between the two shapes.
function sessionForBuildEvent(identity) {
  return { study_id: identity.studyId, participant_id: identity.participantId, tz: identity.tz };
}

// Sleeping if the most recent event is a SLEEP with no WAKE after it.
async function computeState() {
  var hist = await getHistory();
  if (!hist.length) return 'AWAKE';
  return hist[0].marker === 'SLEEP' ? 'SLEEPING' : 'AWAKE';
}

// The open SLEEP event, if the user is currently asleep.
async function topSleep() {
  var hist = await getHistory();
  return (hist.length && hist[0].marker === 'SLEEP') ? hist[0] : null;
}

// If asleep for >= AUTO_WAKE_HOURS, auto-log a wake on app open. Does not open the survey --
// the participant did not just tap Wake, so nothing has established they are present to answer
// it. The night stays completable later through history's completion entry point.
async function maybeAutoWake() {
  var sleep = await topSleep();
  if (!sleep) return false;
  var identity = getSessionIdentity();
  if (!identity) return false;
  var hours = (Date.now() - Number(sleep.event_epoch_ms)) / 3600000;
  if (hours < AUTO_WAKE_HOURS) return false;
  var ev = buildEvent('WAKE', sessionForBuildEvent(identity));
  ev.auto = true; // local display flag only
  await recordEvent(ev);
  toast('Auto-logged wake (12h elapsed)');
  return true;
}

async function applyHomeState() {
  await maybeAutoWake();
  var st = await computeState();
  if (st === 'SLEEPING') {
    var s = await topSleep();
    var label = fmtClock(s.event_epoch_ms, s.event_tz);
    if (!sameDay(s.event_epoch_ms, s.event_tz)) {
      label = new Date(s.event_epoch_ms)
        .toLocaleDateString('en-US', { timeZone: s.event_tz, weekday: 'short' }) + ' ' + label;
    }
    document.getElementById('asleep-since').textContent = 'Since ' + label;
    showOverlay(true);
  } else {
    showOverlay(false);
  }
  await renderStatus();
}

async function renderStatus() {
  var chip = document.getElementById('status-chip');
  chip.textContent = (await computeState()) === 'SLEEPING' ? 'Are you ready to wake up?' : 'Are you going to sleep?';
}

// Tapping Sleep means "I am trying to go to sleep now" -- not bedtime, and not lights-out.
// Getting into and out of bed are separate questions in the morning diary (architecture.md
// section 3.4.2).
async function onSleep() {
  var identity = getSessionIdentity();
  if (!identity) { show('screen-login'); return; }
  await recordEvent(buildEvent('SLEEP', sessionForBuildEvent(identity)));
  toast('Sleep logged ' + fmtClock(Date.now(), identity.tz));
  applyHomeState();
}

// Tapping Wake means "I woke up for the last time" -- getting out of bed is asked separately as
// Q07. Opens the morning survey immediately, prefilled from this WAKE and the SLEEP it closes,
// per architecture.md section 3.4.2.
async function onWake() {
  var identity = getSessionIdentity();
  if (!identity) { show('screen-login'); return; }
  var sleepEvent = await topSleep(); // read before recording, which flips the computed state
  var wakeEvent = buildEvent('WAKE', sessionForBuildEvent(identity));
  await recordEvent(wakeEvent);
  showOverlay(false);
  openSurveyForNight(sleepEvent, wakeEvent);
}

// Appends a raw marker/edit/survey draft to the offline queue. The queued payload never carries
// a credential -- toLogMarkerPayload/toUpdateMarkerPayload/toLogSurveyPayload attach the current
// device token only at send time, so a queue item sitting on disk for days is never a stored
// secret.
function enqueue(kind, payload) {
  return updateQueue(function (q) {
    q.push({ queue_id: uuid(), kind: kind, payload: payload, enqueued_at: new Date().toISOString() });
    return q;
  });
}
function dequeue(queueId) {
  return updateQueue(function (q) { return q.filter(function (item) { return item.queue_id !== queueId; }); });
}

// Every marker record_id that still has a queue item waiting to be confirmed -- the "not yet
// sent" indicator history.js shows next to a Sleep or Wake time. Covers both a fresh marker
// (kind 'marker') and a queued edit to one (kind 'marker_edit'), since either leaves the
// participant's own device unsure whether the Sheet has caught up yet.
async function queuedRecordIds() {
  var q = await getQueue();
  var ids = {};
  q.forEach(function (item) {
    if (item.kind === 'marker' && item.payload) ids[item.payload.record_id] = true;
    else if (item.kind === 'marker_edit' && item.payload && item.payload.event) {
      ids[item.payload.event.record_id] = true;
    }
  });
  return ids;
}

// Every survey_id that still has a queue item waiting to be confirmed -- the "not yet sent"
// indicator history.js's per-night status shows once a survey has been submitted, skipped, or
// abandoned locally but not yet acknowledged by the server.
async function queuedSurveyIds() {
  var q = await getQueue();
  var ids = {};
  q.forEach(function (item) {
    if (item.kind === 'survey' && item.payload) ids[item.payload.survey_id] = true;
  });
  return ids;
}

function payloadForQueueItem(item) {
  if (item.kind === 'marker') return toLogMarkerPayload(item.payload);
  if (item.kind === 'marker_edit') return toUpdateMarkerPayload(item.payload.event, item.payload.client_edit_utc);
  if (item.kind === 'survey') return toLogSurveyPayload(item.payload);
  return null;
}
function senderForQueueItem(item) {
  if (item.kind === 'marker') return logMarker;
  if (item.kind === 'marker_edit') return updateMarker;
  if (item.kind === 'survey') return logSurvey;
  return null;
}

// Reasons the server will never accept no matter how many times the same item is resent. Left
// queued, one of these would jam every later item behind it forever, so these are dropped (with
// a message) rather than retried -- the same treatment section 14.1 already gives invalid_login,
// extended to the completion-guard and edit-window reasons a survey resend can also hit.
var QUEUE_TERMINAL_REASONS = [
  'invalid_login', 'already_answered', 'edit_window_expired', 'invalid_payload', 'not_found'
];

// Drains the offline queue oldest-first, one item at a time. Nothing leaves the queue until the
// server actually confirms it; a transport failure or a transient server reason (busy) halts the
// drain until the next trigger -- boot when online, the 'online' event, or right after
// enqueueing -- so a server problem cannot turn into a flood of retries, and items keep their
// original order.
async function flushQueue() {
  var q = await getQueue();
  if (!q.length) return;
  var item = q[0];
  var payload = payloadForQueueItem(item);
  var sender = senderForQueueItem(item);
  if (!payload || !sender) { await dequeue(item.queue_id); return flushQueue(); } // unrecognised kind

  sender(payload, function (ok, res) {
    if (!ok) return; // request never completed: stop the drain, retry later

    if (res && res.ok) {
      dequeue(item.queue_id).then(flushQueue);
      return;
    }
    if (res && res.reason === 'device_not_recognized') {
      softSignOut(REASON_MESSAGES.device_not_recognized); // stops the drain; queue is untouched
      return;
    }
    if (res && QUEUE_TERMINAL_REASONS.indexOf(res.reason) !== -1) {
      toast(REASON_MESSAGES[res.reason] || 'This entry could not be sent.');
      dequeue(item.queue_id).then(flushQueue);
      return;
    }
    // Any other reason (busy, or one this build does not recognise): stop the drain, retry later.
  });
}

// append locally + enqueue + attempt to send now (falls back to the offline queue automatically
// if the attempt does not complete)
async function recordEvent(ev) {
  await updateHistory(function (hist) { hist.unshift(ev); return hist; });
  await enqueue('marker', ev);
  flushQueue();
}

// Question IDs Q01-Q08 are the shipped Consensus Sleep Diary Core items (architecture.md
// section 3.4.1); anything else visible was added by the researcher on QuestionsSetup. The
// standalone build's own participant-authored questions (question_source 'participant') are
// Phase 5 scope and do not exist yet.
var DEFAULT_QUESTION_IDS = ['Q01', 'Q02', 'Q03', 'Q04', 'Q05', 'Q06', 'Q07', 'Q08'];
function questionSourceFor(questionId) {
  return DEFAULT_QUESTION_IDS.indexOf(questionId) !== -1 ? 'default' : 'researcher';
}

var surveyDraft = null;   // the in-progress survey; see initSurveyDraft
var surveyQuestions = []; // the visible question list this draft is being answered against
var surveyAnswerCounter = 1;

function escapeHtml(s) {
  return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
  });
}

// Reads the question list to render this survey against: the cached copy of getConfig's last
// successful fetch first, so an offline participant still sees their study's own questions, then
// a fresh network fetch to keep it current, then the hardcoded default as a last resort.
async function loadSurveyQuestions() {
  var cached = await getCachedConfig();
  if (cached && Array.isArray(cached.questions) && cached.questions.length) {
    surveyQuestions = cached.questions;
  } else {
    surveyQuestions = DEFAULT_QUESTIONS || [];
  }
  getConfig(function (cfg) {
    if (cfg) {
      if (Array.isArray(cfg.questions)) surveyQuestions = cfg.questions;
      setCachedConfig(cfg);
    }
  }, function () {}); // offline: keep whatever loaded above
  return surveyQuestions;
}

// One unanswered SurveyAnswers row per visible question, per architecture.md section 3.6: every
// question shown gets a row, whether or not it is ever answered.
function buildAnswerSkeleton(question, displayOrder) {
  return {
    record_id: uuid(),
    question_id: question.question_id,
    question_source: questionSourceFor(question.question_id),
    answer_type: question.answer_type,
    question_text_shown: question.display_text,
    required: !!question.required,
    display_order: displayOrder,
    answer_order: '',
    value: '',
    value_number: '',
    value_unit: '',
    answered_utc: '',
    edited_utc: '',
    edit_count: 0,
    time_to_answer_ms: ''
  };
}

function findAnswer(questionId) {
  return surveyDraft.answers.filter(function (a) { return a.question_id === questionId; })[0];
}
function findQuestion(questionId) {
  return surveyQuestions.filter(function (q) { return q.question_id === questionId; })[0];
}

// Marks an answer's first value. Only called once per answer; later changes go through
// markEdited instead, so answered_utc always names the moment the participant first responded,
// per data-dictionary.md's "empty means shown but not answered."
function markAnswered(answer) {
  answer.answer_order = surveyAnswerCounter++;
  answer.answered_utc = new Date().toISOString();
  answer.time_to_answer_ms = Date.parse(answer.answered_utc) - Date.parse(surveyDraft.survey_opened_utc);
}
function markEdited(answer) {
  answer.edited_utc = new Date().toISOString();
  answer.edit_count = (answer.edit_count || 0) + 1;
}

// ----- building a fresh draft -----

// identity: {study_id, participant_id, tz} (event.js's shape, not the vault session's). A
// resumed survey_id (history.js's completion entry point) always starts from a fresh, empty
// draft: history.js only offers resuming a record that is not locked, and an unlocked
// skipped/abandoned record has zero answers by definition (isSurveyLocked), so there is nothing
// to restore -- only the identifier (survey_id) is reused, so the eventual write updates the
// existing Surveys row instead of adding a second one.
function initSurveyDraft(surveyId, sleepDay, identity, sleepEvent, wakeEvent) {
  surveyAnswerCounter = 1;
  surveyDraft = {
    survey_id: surveyId,
    study_id: identity.study_id,
    participant_id: identity.participant_id,
    sleep_day: sleepDay,
    sleep_record_id: sleepEvent ? sleepEvent.record_id : '',
    wake_record_id: wakeEvent ? wakeEvent.record_id : '',
    wake_marker_utc: wakeEvent ? wakeEvent.event_utc : '',
    survey_opened_utc: new Date().toISOString(),
    survey_ended_utc: '',
    end_reason: '',
    event_tz: identity.tz,
    tz_offset_minutes: Math.round(tzOffsetMs(new Date(), identity.tz) / 60000),
    answers: surveyQuestions.map(function (q, i) { return buildAnswerSkeleton(q, i + 1); })
  };
  applyPrefill(sleepEvent, wakeEvent);
}

// Q02/Q06-style questions (prefill_from SLEEP_MARKER/WAKE_MARKER) open already filled in from
// the marker's own local time. The participant may change the answer; the marker itself never
// changes, per architecture.md section 3.4.2.
function applyPrefill(sleepEvent, wakeEvent) {
  surveyDraft.answers.forEach(function (answer) {
    var question = findQuestion(answer.question_id);
    if (!question || !question.prefill_from) return;
    var source = question.prefill_from === 'SLEEP_MARKER' ? sleepEvent
      : question.prefill_from === 'WAKE_MARKER' ? wakeEvent : null;
    if (!source) return;
    answer.value = source.event_local;
    answer.value_number = minutesFromMidnight(source.event_local);
    answer.value_unit = 'hh:mm';
    markAnswered(answer);
  });
}

function minutesFromMidnight(localIso) {
  var m = /T(\d{2}):(\d{2})/.exec(String(localIso || ''));
  return m ? Number(m[1]) * 60 + Number(m[2]) : '';
}

// ----- rendering -----

// `|| defaultValue` would silently turn a legitimate min_value of 0 into 1 (0 is falsy), so a
// missing value is checked for explicitly rather than relied on to fall through.
function numberOr(value, fallback) {
  return value === '' || value == null ? fallback : Number(value);
}

function optionsForButtons(question) {
  if (question.answer_type === 'boolean') {
    return [{ value: 'Yes', label: 'Yes' }, { value: 'No', label: 'No' }];
  }
  var opts = [];
  var min = numberOr(question.min_value, 1), max = numberOr(question.max_value, 5);
  for (var v = min; v <= max; v++) {
    opts.push({ value: String(v), label: String(v) });
  }
  return opts;
}

function renderControl(question, answer) {
  var id = 'ctrl-' + question.question_id;
  var label = escapeHtml(question.display_text);

  if (question.input_style === 'slider') {
    var min = Number(question.min_value) || 0, max = Number(question.max_value) || 10;
    var current = answer.answered_utc ? Number(answer.value) : min;
    return '' +
      '<div class="slider-control">' +
        '<input type="range" id="' + id + '" class="' + (answer.answered_utc ? '' : 'untouched') + '" ' +
          'min="' + min + '" max="' + max + '" value="' + current + '" data-qid="' + question.question_id + '" ' +
          'aria-label="' + label + '">' +
        '<div class="slider-row">' +
          '<button type="button" class="step-minus" data-qid="' + question.question_id + '" aria-label="Decrease">&minus;</button>' +
          '<div class="slider-readout"><span>' + escapeHtml(question.min_label || '') + '</span>' +
            '<span class="slider-value" id="val-' + question.question_id + '">' + (answer.answered_utc ? current : '') + '</span>' +
            '<span>' + escapeHtml(question.max_label || '') + '</span></div>' +
          '<button type="button" class="step-plus" data-qid="' + question.question_id + '" aria-label="Increase">+</button>' +
        '</div>' +
      '</div>';
  }

  if (question.input_style === 'stepper') {
    var smin = Number(question.min_value) || 0, smax = Number(question.max_value) || 999;
    var sval = answer.answered_utc ? answer.value : '';
    var atMax = answer.answered_utc && Number(answer.value) === smax;
    return '' +
      '<div class="stepper-control">' +
        '<button type="button" class="step-minus" data-qid="' + question.question_id + '" aria-label="Decrease">&minus;</button>' +
        '<input type="number" inputmode="numeric" id="' + id + '" min="' + smin + '" max="' + smax + '" ' +
          'value="' + sval + '" data-qid="' + question.question_id + '" aria-label="' + label + '">' +
        '<button type="button" class="step-plus" data-qid="' + question.question_id + '" aria-label="Increase">+</button>' +
        '<span class="stepper-unit" id="note-' + question.question_id + '">' +
          (atMax ? (smax + ' or more') : escapeHtml(question.unit || '')) + '</span>' +
      '</div>';
  }

  if (question.input_style === 'buttons') {
    var options = optionsForButtons(question);
    return '' +
      '<fieldset class="buttons-control" data-qid="' + question.question_id + '">' +
        '<legend class="visually-hidden">' + label + '</legend>' +
        (question.min_label ? '<span class="button-end-label">' + escapeHtml(question.min_label) + '</span>' : '') +
        '<div class="button-row">' + options.map(function (opt) {
          var checked = answer.answered_utc && String(answer.value) === opt.value ? ' checked' : '';
          return '<label class="button-option"><input type="radio" name="' + id + '" value="' + opt.value + '"' +
            checked + ' data-qid="' + question.question_id + '"><span>' + escapeHtml(opt.label) + '</span></label>';
        }).join('') + '</div>' +
        (question.max_label ? '<span class="button-end-label">' + escapeHtml(question.max_label) + '</span>' : '') +
      '</fieldset>';
  }

  if (question.answer_type === 'datetime') {
    var dParts = answer.answered_utc ? /^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2})/.exec(answer.value) : null;
    return '' +
      '<div class="datetime-control">' +
        '<input type="date" id="' + id + '-date" data-qid="' + question.question_id + '" data-part="date" ' +
          'value="' + (dParts ? dParts[1] : '') + '" aria-label="' + label + ' date">' +
        '<input type="time" id="' + id + '-time" data-qid="' + question.question_id + '" data-part="time" ' +
          'value="' + (dParts ? dParts[2] : '') + '" aria-label="' + label + ' time">' +
      '</div>';
  }

  // 'time' -- the common case. The participant picks a clock time only; the calendar date
  // follows from sleep_day, per architecture.md section 4.1.
  var tParts = answer.answered_utc ? /T(\d{2}:\d{2})/.exec(answer.value) : null;
  return '<input type="time" id="' + id + '" data-qid="' + question.question_id + '" ' +
    'value="' + (tParts ? tParts[1] : '') + '" aria-label="' + label + '">';
}

function renderSurveyQuestions() {
  var box = document.getElementById('survey-questions');
  box.innerHTML = surveyQuestions.map(function (question) {
    var answer = findAnswer(question.question_id);
    return '' +
      '<div class="question">' +
        '<p class="q-text">' + escapeHtml(question.display_text) +
          (question.required ? ' <span class="required-badge">Required</span>' : '') + '</p>' +
        renderControl(question, answer) +
      '</div>';
  }).join('');
  updateSurveyButtons();
}

function unansweredRequired() {
  return surveyDraft.answers.filter(function (a) { return a.required && !a.answered_utc; });
}
function answeredCount() {
  return surveyDraft.answers.filter(function (a) { return a.answered_utc; }).length;
}

// Skip is only offered while nothing has been answered yet; once anything has, walking away
// would misrepresent engagement, so Cancel (which sends what exists as abandoned) takes its
// place. Submit appears once every visible required question has an answer.
function updateSurveyButtons() {
  var count = answeredCount();
  document.getElementById('btn-survey-skip').classList.toggle('hidden', count > 0);
  document.getElementById('btn-survey-cancel').classList.toggle('hidden', count === 0);
  document.getElementById('btn-survey-submit').disabled = unansweredRequired().length > 0;
  document.getElementById('survey-required-error').textContent = '';
}

// ----- control interaction -----

// Slider dragging and typing into a stepper's number field both fire many 'input' events in a
// row. Rebuilding the whole question list on each one -- survey.js's usual pattern for any
// other change -- would destroy and recreate the very control the participant has a finger or a
// cursor in, losing the drag or the keystroke. Both update the answer and the small pieces of
// their own markup directly instead; every other control (a single discrete tap or a native
// picker committing a finished value) still goes through the full rebuild, which is simpler and
// carries no such cost.
function onSurveyInput(e) {
  var target = e.target;
  var qid = target.getAttribute('data-qid');
  if (!qid) return;
  var answer = findAnswer(qid);
  var question = findQuestion(qid);
  if (!answer || !question) return;
  var wasAnswered = !!answer.answered_utc;

  if (question.input_style === 'slider') {
    if (target.value === '') return;
    setAnswerFromClockOrNumber(question, answer, target.value);
    if (!wasAnswered) markAnswered(answer); else markEdited(answer);
    target.classList.remove('untouched');
    var readout = document.getElementById('val-' + qid);
    if (readout) readout.textContent = answer.value;
    updateSurveyButtons();
    return;
  }

  if (question.input_style === 'stepper') {
    if (target.value === '') return;
    setAnswerFromClockOrNumber(question, answer, target.value);
    if (!wasAnswered) markAnswered(answer); else markEdited(answer);
    updateStepperNote(question, answer);
    updateSurveyButtons();
    return;
  }

  var set;
  if (question.answer_type === 'time') {
    if (target.value === '') return;
    set = setAnswerFromClockOrNumber(question, answer, target.value);
  } else if (question.answer_type === 'datetime') {
    // Only one of the date/time pair may have a value yet; wait for both before recording an
    // answer, so half a datetime is never marked as though the participant had finished it.
    set = setAnswerFromDatetimeParts(question, answer);
  } else {
    return; // radios are handled on 'change' below
  }
  if (!set) return;
  if (!wasAnswered) markAnswered(answer); else markEdited(answer);
  // A native time/date picker's own display already shows what was just chosen; only the
  // Submit/Skip/Cancel state can change here, not anything the question list itself renders.
  updateSurveyButtons();
}

function updateStepperNote(question, answer) {
  var note = document.getElementById('note-' + question.question_id);
  if (!note) return;
  var max = Number(question.max_value) || 999;
  note.textContent = Number(answer.value) === max ? (max + ' or more') : (question.unit || '');
}

function onSurveyChange(e) {
  var target = e.target;
  if (target.type !== 'radio') return;
  var qid = target.getAttribute('data-qid');
  var answer = findAnswer(qid);
  var question = findQuestion(qid);
  if (!answer || !question || !target.checked) return;
  var wasAnswered = !!answer.answered_utc;

  if (question.answer_type === 'boolean') {
    answer.value = target.value;
    answer.value_number = target.value === 'Yes' ? 1 : 0;
    answer.value_unit = '';
  } else {
    answer.value = target.value;
    answer.value_number = Number(target.value);
    answer.value_unit = 'points';
  }
  if (!wasAnswered) markAnswered(answer); else markEdited(answer);
  renderSurveyQuestions();
}

// @return {boolean} True if the answer was actually set.
function setAnswerFromClockOrNumber(question, answer, rawValue) {
  if (question.answer_type === 'time') {
    var iso = localIsoForTimeAnswer(surveyDraft.sleep_day, rawValue, surveyDraft.event_tz);
    answer.value = iso;
    answer.value_number = minutesFromMidnight(iso);
    answer.value_unit = 'hh:mm';
    return true;
  }
  // stepper (duration_minutes, count) or a slider (scale, ordinal, count, duration_minutes)
  var num = Number(rawValue);
  answer.value = num;
  answer.value_number = num;
  answer.value_unit = question.answer_type === 'duration_minutes' ? 'minutes'
    : (question.answer_type === 'scale' || question.answer_type === 'ordinal') ? 'points'
    : (question.unit || '');
  return true;
}

// @return {boolean} True only once both the date and the time sub-field carry a value.
function setAnswerFromDatetimeParts(question, answer) {
  var dateEl = document.getElementById('ctrl-' + question.question_id + '-date');
  var timeEl = document.getElementById('ctrl-' + question.question_id + '-time');
  if (!dateEl.value || !timeEl.value) return false;
  var iso = localIsoForDatetimeAnswer(dateEl.value, timeEl.value, surveyDraft.event_tz);
  answer.value = iso;
  answer.value_number = minutesFromMidnight(iso);
  answer.value_unit = 'hh:mm';
  return true;
}

function onSurveyStep(e) {
  var btn = e.target.closest('.step-minus, .step-plus');
  if (!btn) return;
  var qid = btn.getAttribute('data-qid');
  var question = findQuestion(qid);
  var answer = findAnswer(qid);
  if (!question || !answer) return;
  var min = Number(question.min_value) || 0, max = Number(question.max_value) || 999;
  var current = answer.answered_utc ? Number(answer.value) : min;
  var next = btn.classList.contains('step-minus') ? current - 1 : current + 1;
  next = Math.max(min, Math.min(max, next));
  var wasAnswered = !!answer.answered_utc;
  answer.value = next;
  answer.value_number = next;
  answer.value_unit = question.answer_type === 'duration_minutes' ? 'minutes'
    : question.answer_type === 'scale' || question.answer_type === 'ordinal' ? 'points'
    : (question.unit || '');
  if (!wasAnswered) markAnswered(answer); else markEdited(answer);
  renderSurveyQuestions();
}

// ----- opening the screen -----

async function openSurveyScreen(title) {
  document.getElementById('survey-title').textContent = title;
  renderSurveyQuestions();
  show('screen-survey');
}

// Entry point 1: right after waking, for tonight's own survey.
async function openSurveyForNight(sleepEvent, wakeEvent) {
  var identity = getSessionIdentity();
  if (!identity) return;
  var sleepDay = sleepEvent ? sleepDayFromLocal(sleepEvent.event_local)
    : findPrecedingSleepDayLocal(await getHistory(), wakeEvent.event_epoch_ms, wakeEvent.event_local);
  await loadSurveyQuestions();
  initSurveyDraft(uuid(), sleepDay, sessionForBuildEvent(identity), sleepEvent, wakeEvent);
  await openSurveyScreen('Morning diary');
}

// Entry point 2: completing a skipped or missing survey from history, within edit_window_days of
// the night itself (architecture.md section 10). night is {sleepDay, sleepEvent, wakeEvent,
// existingRecord}, where existingRecord is the local surveys-collection entry if one already
// exists (reused rather than starting a new survey_id) or null (a night with a marker and no
// locally known survey at all).
async function openSurveyForCompletion(night) {
  var identity = getSessionIdentity();
  if (!identity) return;
  await loadSurveyQuestions();
  var surveyId = night.existingRecord ? night.existingRecord.survey_id : uuid();
  initSurveyDraft(surveyId, night.sleepDay, sessionForBuildEvent(identity), night.sleepEvent, night.wakeEvent);
  await openSurveyScreen('Complete diary for ' + night.sleepDay);
}

function closeSurveyScreen() {
  surveyDraft = null;
  show('screen-home');
  applyHomeState();
}

// ----- finishing: submit, skip, cancel -----

async function persistAndSend(endReason) {
  surveyDraft.survey_ended_utc = new Date().toISOString();
  surveyDraft.end_reason = endReason;
  var record = Object.assign({}, surveyDraft);
  await updateSurveys(function (list) {
    var i = list.findIndex(function (s) { return s.survey_id === record.survey_id; });
    if (i === -1) list.push(record); else list[i] = record;
    return list;
  });
  await enqueue('survey', record);
  flushQueue();
}

async function doSurveySubmit() {
  var missing = unansweredRequired();
  if (missing.length) {
    document.getElementById('survey-required-error').textContent =
      'Please answer every required question before submitting.';
    return;
  }
  await persistAndSend('submitted');
  toast('Diary submitted');
  closeSurveyScreen();
}

// Only reachable with zero answers so far (updateSurveyButtons hides the button otherwise).
async function doSurveySkip() {
  await persistAndSend('skipped');
  toast('Diary skipped');
  closeSurveyScreen();
}

// Only reachable with at least one answer already given; sends what exists immediately rather
// than waiting for a later sweep to infer abandonment.
async function doSurveyCancel() {
  await persistAndSend('abandoned');
  toast('Diary saved as abandoned');
  closeSurveyScreen();
}

// ----- wire payload for the offline queue (state.js calls this by name) -----

function toLogSurveyPayload(draft) {
  return {
    study_id: draft.study_id,
    participant_id: draft.participant_id,
    device_token: getSessionToken(),
    survey_id: draft.survey_id,
    target_sleep_day: draft.sleep_day,
    sleep_record_id: draft.sleep_record_id || '',
    wake_record_id: draft.wake_record_id || '',
    wake_marker_utc: draft.wake_marker_utc || '',
    survey_opened_utc: draft.survey_opened_utc,
    survey_ended_utc: draft.survey_ended_utc || '',
    end_reason: draft.end_reason,
    event_tz: draft.event_tz || '',
    tz_offset_minutes: draft.tz_offset_minutes || 0,
    source: 'web',
    app_version: APP_VERSION,
    answers: draft.answers.map(function (a) {
      return {
        record_id: a.record_id, question_id: a.question_id, question_source: a.question_source,
        answer_type: a.answer_type, question_text_shown: a.question_text_shown,
        required: a.required, display_order: a.display_order, answer_order: a.answer_order,
        value: a.value, value_number: a.value_number, value_unit: a.value_unit,
        answered_utc: a.answered_utc, edited_utc: a.edited_utc, edit_count: a.edit_count,
        time_to_answer_ms: a.time_to_answer_ms
      };
    })
  };
}

// Whether a locally-known survey record is locked -- submitted outright, or ended with at least
// one answer given -- mirroring logSurvey's own guard so history.js never offers a completion
// entry point the server would refuse anyway.
function isSurveyLocked(record) {
  if (!record) return false;
  if (record.end_reason === 'submitted') return true;
  return (record.end_reason === 'skipped' || record.end_reason === 'abandoned')
    && record.answers.some(function (a) { return a.answered_utc; });
}
