// This file is part of MiNap Go
// core.js
// Author(s): Gabriel Mongefranco
// Created: 2026-08-19
// Last Modified: 2026-08-19
// Summary: Storage and domain-rule logic for the MiNap Go client, merged from src/data/ and src/logic/.
// Notes: See README file for documentation and full license information.
// Generated by build.py from src/data/, src/logic/. Do not edit directly; edit the source and rerun build.py.
//
// Copyright © 2026 The Regents of the University of Michigan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along
// with this program. If not, see <https://www.gnu.org/licenses/>.

// PBKDF2 iteration count for turning a login PIN into a key-wrapping key. Reused from the
// 310,000 the private-notes vault spec (architecture.md section 6.1) commits to, for internal
// consistency -- it is the one client-side PBKDF2 number this project's own documentation has
// settled on. Stored per profile as pin_iterations, so a device that wrapped its key at a lower
// count can be raised to the current one on a later unlock without breaking anything.
var PBKDF2_ITERATIONS = 310000;
var PBKDF2_HASH = 'SHA-256';
var WRAP_ALGORITHM = 'AES-GCM';
var WRAP_KEY_LENGTH = 256;
var SALT_BYTES = 16;
var IV_BYTES = 12;

function randomBytes(length) {
  return crypto.getRandomValues(new Uint8Array(length));
}

// A fresh random salt for deriving a PIN-wrapping key. Unrelated to the server's own pin_salt
// column: the server salts and stretches the PIN separately (10-round chained SHA-256, to check
// a submitted PIN) from this client-side PBKDF2 salt (to derive a key that wraps the local data
// key). Same field name in two unconnected places; the two values are never compared.
function randomSalt() {
  return randomBytes(SALT_BYTES);
}

function toBase64(bytes) {
  var bin = '';
  for (var i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}
function fromBase64(b64) {
  var bin = atob(b64);
  var bytes = new Uint8Array(bin.length);
  for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

// Derives a non-extractable AES-GCM key from a PIN, a salt, and an iteration count. The PIN
// itself is never stored; only the salt and iteration count needed to re-derive this key are.
function deriveWrappingKey(pin, saltBytes, iterations) {
  return crypto.subtle.importKey(
    'raw', new TextEncoder().encode(String(pin)), 'PBKDF2', false, ['deriveKey']
  ).then(function (baseKey) {
    return crypto.subtle.deriveKey(
      { name: 'PBKDF2', salt: saltBytes, iterations: iterations, hash: PBKDF2_HASH },
      baseKey,
      { name: WRAP_ALGORITHM, length: WRAP_KEY_LENGTH },
      false, // non-extractable: only ever used to wrap/unwrap, never exported
      ['wrapKey', 'unwrapKey']
    );
  });
}

// A random AES-GCM data key. Extractable is required so SubtleCrypto can wrap it for storage;
// this is not a separate exposure, because the wrapped bytes are themselves only readable
// through the PIN-derived wrapping key.
function generateDataKey() {
  return crypto.subtle.generateKey({ name: WRAP_ALGORITHM, length: WRAP_KEY_LENGTH }, true, ['encrypt', 'decrypt']);
}

// A device key SubtleCrypto generates and holds itself: non-extractable, so no code running on
// this page -- including this file -- can ever read its raw bytes back out, only ask the browser
// to wrap/unwrap or encrypt/decrypt with it. It wraps a second copy of the data key and encrypts
// the stored device token, which is what lets a return visit resume with no PIN prompt.
//
// What that actually buys: protection against page script exporting the key, whether by an
// injection or by a bug in this app's own code. It does not protect against someone with the
// device itself on a rooted or jailbroken phone, where the browser's own on-disk form of the key
// can be recovered outside the page sandbox entirely. The device token being revocable from the
// Sheet and useless anywhere else is what actually limits a stolen phone's exposure; this key is
// a second layer on top of that, not the layer doing the real work. See docs/architecture.md
// section 5.6, and storage.js's probeCryptoKeyStorage, which checks this holds before relying on
// it rather than assuming so.
function generateDeviceKey() {
  return crypto.subtle.generateKey(
    { name: WRAP_ALGORITHM, length: WRAP_KEY_LENGTH }, false, ['wrapKey', 'unwrapKey', 'encrypt', 'decrypt']
  );
}

// Wraps dataKey under wrappingKey. The returned iv and wrapped bytes are safe to store in the
// clear -- the wrapping key, not secrecy of these bytes, is what protects the data key.
function wrapDataKey(dataKey, wrappingKey) {
  var iv = randomBytes(IV_BYTES);
  return crypto.subtle.wrapKey('raw', dataKey, wrappingKey, { name: WRAP_ALGORITHM, iv: iv })
    .then(function (wrapped) {
      return { iv: toBase64(iv), wrapped: toBase64(new Uint8Array(wrapped)) };
    });
}

// Unwraps a data key. A wrong wrappingKey (wrong PIN) makes this promise reject, because
// AES-GCM's own authentication tag check fails -- that rejection is the sole "wrong PIN"
// signal; no separate verifier value is stored. (IndexedDB corruption of the stored bytes would
// also make this reject, indistinguishable from a wrong PIN -- both are simply "cannot unwrap.")
function unwrapDataKey(wrappedRecord, wrappingKey) {
  return crypto.subtle.unwrapKey(
    'raw', fromBase64(wrappedRecord.wrapped), wrappingKey,
    { name: WRAP_ALGORITHM, iv: fromBase64(wrappedRecord.iv) },
    { name: WRAP_ALGORITHM, length: WRAP_KEY_LENGTH },
    true, ['encrypt', 'decrypt']
  );
}

// Encrypts one JSON-serializable value under dataKey. A fresh random iv is drawn on every call
// and never reused -- AES-GCM fails catastrophically if the same key/iv pair is ever repeated.
function encryptJSON(dataKey, value) {
  var iv = randomBytes(IV_BYTES);
  var plaintext = new TextEncoder().encode(JSON.stringify(value));
  return crypto.subtle.encrypt({ name: WRAP_ALGORITHM, iv: iv }, dataKey, plaintext).then(function (ciphertext) {
    return { iv: toBase64(iv), ciphertext: toBase64(new Uint8Array(ciphertext)) };
  });
}

function decryptJSON(dataKey, record) {
  return crypto.subtle.decrypt(
    { name: WRAP_ALGORITHM, iv: fromBase64(record.iv) }, dataKey, fromBase64(record.ciphertext)
  ).then(function (plaintext) {
    return JSON.parse(new TextDecoder().decode(plaintext));
  });
}

var DB_NAME = 'minap-go';
var DB_VERSION = 1;
var STORE_NAME = 'kv';

// DB_VERSION and this upgrade handler are only for object-store *structure* changes (a new
// store, a new index). They run before any PIN is entered and cannot decrypt anything, so a
// change to what is inside an encrypted record's plaintext is a vault.js concern (see that
// file's content_version handling), not a reason to bump this number.
var dbPromise = null;
function openDb() {
  if (dbPromise) return dbPromise;
  dbPromise = new Promise(function (resolve, reject) {
    var req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = function () {
      var db = req.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: 'key' });
      }
    };
    req.onsuccess = function () { resolve(req.result); };
    req.onerror = function () { reject(req.error); };
  });
  return dbPromise;
}

function getRecord(key) {
  return openDb().then(function (db) {
    return new Promise(function (resolve, reject) {
      var tx = db.transaction(STORE_NAME, 'readonly');
      var req = tx.objectStore(STORE_NAME).get(key);
      req.onsuccess = function () { resolve(req.result || null); };
      req.onerror = function () { reject(req.error); };
    });
  });
}

// record.value can be any structured-cloneable JavaScript value, not only plain JSON -- IndexedDB
// clones it natively. In particular a CryptoKey clones and reads back as a live, usable key with
// no special handling here, which is what lets vault.js store a non-extractable device key
// through this same function rather than needing a separate code path for it.
function putRecord(record) {
  return openDb().then(function (db) {
    return new Promise(function (resolve, reject) {
      var tx = db.transaction(STORE_NAME, 'readwrite');
      tx.objectStore(STORE_NAME).put(record);
      tx.oncomplete = function () { resolve(); };
      tx.onerror = function () { reject(tx.error); };
    });
  });
}

function deleteRecord(key) {
  return openDb().then(function (db) {
    return new Promise(function (resolve, reject) {
      var tx = db.transaction(STORE_NAME, 'readwrite');
      tx.objectStore(STORE_NAME).delete(key);
      tx.oncomplete = function () { resolve(); };
      tx.onerror = function () { reject(tx.error); };
    });
  });
}

// Feature-detects whether this browser actually stores and returns a usable non-extractable
// CryptoKey through IndexedDB, rather than assuming crypto.js's generateDeviceKey design works
// everywhere it might run. Generates a throwaway key, round-trips it through a scratch record,
// and confirms what comes back still behaves like a secret key. Cleans up the scratch record
// either way, and never throws: any failure here just means the answer is false.
//
// architecture.md section 5.6 measures this as true on desktop Chrome inside the Apps Script
// frame, including across a reload, and flags iOS Safari as still unverified -- run this there
// and report the result honestly rather than assuming it holds.
function probeCryptoKeyStorage() {
  var PROBE_KEY = 'crypto_key_storage_probe';
  return crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt'])
    .then(function (key) {
      return putRecord({ key: PROBE_KEY, value: key });
    })
    .then(function () {
      return getRecord(PROBE_KEY);
    })
    .then(function (rec) {
      var usable = !!(rec && rec.value && rec.value.type === 'secret');
      return deleteRecord(PROBE_KEY).then(function () { return usable; });
    })
    .catch(function () {
      return deleteRecord(PROBE_KEY).catch(function () {}).then(function () { return false; });
    });
}

// The unwrapped data key and the device token live only here, only in memory, only for as long
// as the vault is unlocked -- never persisted as plaintext outside encrypted or non-extractable
// storage. The PIN itself is never held here at all, at any point: Code.gs's authenticateWrite_
// checks a device token on every write, not the PIN, so nothing in a session's lifetime ever
// needs to re-send it. Holding it would only recreate the exposure splitting the two was meant
// to remove -- a stolen device handing over a secret the participant may have reused elsewhere.
var session = null; // { studyId, participantId, tz, dataKey, deviceToken } | null

var LAST_IDENTITY_KEY = 'last_identity';

// A single Apps Script deployment can serve more than one study sharing one workbook
// (architecture.md section 3.1), and a device could plausibly be used for more than one
// study/participant pair over time. Every record is namespaced by identity so two identities
// used on the same device get fully separate, independently-encrypted data -- never
// overwriting or orphaning one another. The standalone build has no login and only ever one
// local identity, so it falls back to a fixed prefix.
function collectionKey(studyId, participantId, name) {
  var prefix = studyId ? (studyId + '_' + participantId + '_') : 'local_';
  return prefix + name;
}

function readPlain(key) {
  return getRecord(key).then(function (rec) { return rec ? rec.value : null; });
}
function writePlain(key, value) {
  return putRecord({ key: key, value: value });
}

// content_version is separate from storage.js's DB_VERSION: it describes the shape of what is
// *inside* an encrypted record's plaintext, which onupgradeneeded cannot see or migrate (it
// runs before any PIN is entered). A future phase that changes what history/queue/cachedConfig
// hold reads the old content_version after unlock, transforms in JS, and writes it back at the
// current one. Nothing yet needs that transform, so none is implemented.
var CONTENT_VERSION = 1;

function readEncrypted(dataKey, key, fallback) {
  return getRecord(key).then(function (rec) {
    if (!rec) return fallback;
    return decryptJSON(dataKey, rec);
  });
}
function writeEncrypted(dataKey, key, value) {
  return encryptJSON(dataKey, value).then(function (enc) {
    return putRecord(Object.assign({ key: key, content_version: CONTENT_VERSION }, enc));
  });
}

// Per-key write serialization. An async storage layer lets two operations on the same
// collection interleave (a Sleep tap and a queue drain, say) in a way synchronous localStorage
// never could; this keeps a read-modify-write sequence on one key from clobbering another's.
var writeQueues = {};
function serialize(key, fn) {
  var tail = writeQueues[key] || Promise.resolve();
  var result = tail.then(fn, fn);
  writeQueues[key] = result.catch(function () {}); // keep the chain alive past a failed op
  return result;
}

// Atomic read-modify-write on one collection: reads the current value, applies mutatorFn, and
// writes the result, all serialized against any other pending operation on the same key.
function updateCollection(name, mutatorFn, fallback) {
  if (!session) return Promise.reject(new Error('locked'));
  var key = collectionKey(session.studyId, session.participantId, name);
  return serialize(key, function () {
    return readEncrypted(session.dataKey, key, fallback).then(function (current) {
      var updated = mutatorFn(current);
      return writeEncrypted(session.dataKey, key, updated).then(function () { return updated; });
    });
  });
}

// ----- last-used identity, for pre-filling the login screen -----

function getLastIdentity() {
  return readPlain(LAST_IDENTITY_KEY);
}
function setLastIdentity(studyId, participantId) {
  return writePlain(LAST_IDENTITY_KEY, { study_id: studyId, participant_id: participantId });
}
function clearLastIdentity() {
  return deleteRecord(LAST_IDENTITY_KEY);
}

// ----- profile: identity + PIN key material, unencrypted -----
//
// Unencrypted is correct here, not a shortcut: this record has to be readable before the PIN is
// entered, to know whether this device already has a profile for this identity at all. It holds
// the same class of information architecture.md section 6.1's notes vault stores in the clear
// for the same reason -- salt, iteration count, wrapped key -- never the PIN itself, and now
// never the device token in the clear either unless probeCryptoKeyStorage says this browser
// cannot do better (see establishDeviceSession_ below).

function getProfile(studyId, participantId) {
  return readPlain(collectionKey(studyId, participantId, 'profile'));
}

function createLocalProfile(studyId, participantId, tz, pin, deviceToken) {
  var key = collectionKey(studyId, participantId, 'profile');
  var newDataKey;
  return readPlain(key).then(function (existing) {
    if (existing) throw new Error('profile_exists');
    return generateDataKey();
  }).then(function (dataKey) {
    newDataKey = dataKey;
    var salt = randomSalt();
    return deriveWrappingKey(pin, salt, PBKDF2_ITERATIONS).then(function (wrappingKey) {
      return wrapDataKey(dataKey, wrappingKey);
    }).then(function (wrapped) {
      var now = new Date().toISOString();
      return writePlain(key, {
        study_id: studyId,
        participant_id: participantId,
        tz: tz,
        pin_salt: toBase64(salt),
        pin_iterations: PBKDF2_ITERATIONS,
        wrapped_key_iv: wrapped.iv,
        wrapped_key_ciphertext: wrapped.wrapped,
        created_at: now,
        pin_set_at: now
      });
    });
  }).then(function () {
    return establishDeviceSession_(studyId, participantId, newDataKey, deviceToken);
  }).then(function () {
    session = { studyId: studyId, participantId: participantId, tz: tz,
      dataKey: newDataKey, deviceToken: String(deviceToken) };
  });
}

// Attempts a fully local, PIN-only unwrap of a profile already on this device. Returns
// true/false rather than rejecting on a wrong PIN -- a wrong PIN is an expected outcome here,
// not an exceptional one. deviceToken comes from a verifyPin call the caller has already made:
// unwrapping the data key is local and offline-capable on its own, but only the server can mint
// a token, so a caller reaching this function is expected to have one in hand already.
function unlockWithPin(studyId, participantId, pin, deviceToken) {
  return getProfile(studyId, participantId).then(function (profile) {
    if (!profile) return false;
    var salt = fromBase64(profile.pin_salt);
    return deriveWrappingKey(pin, salt, profile.pin_iterations).then(function (wrappingKey) {
      return unwrapDataKey(
        { iv: profile.wrapped_key_iv, wrapped: profile.wrapped_key_ciphertext }, wrappingKey
      ).then(function (dataKey) {
        session = { studyId: studyId, participantId: participantId, tz: profile.tz,
          dataKey: dataKey, deviceToken: String(deviceToken) };
        var upgrade = profile.pin_iterations < PBKDF2_ITERATIONS
          ? rewrapAtCurrentIterations(studyId, participantId, pin, dataKey)
          : Promise.resolve();
        return upgrade
          .then(function () { return establishDeviceSession_(studyId, participantId, dataKey, deviceToken); })
          .then(function () { return true; });
      }, function () {
        return false; // unwrap rejected: wrong PIN (or corrupted data -- see crypto.js comment)
      });
    });
  });
}

// Re-wraps the already-unwrapped data key at the current PBKDF2_ITERATIONS, so a device that
// set its PIN before an iteration-count increase catches up on its next successful unlock,
// without ever needing a forced re-entry of the PIN.
function rewrapAtCurrentIterations(studyId, participantId, pin, dataKey) {
  var key = collectionKey(studyId, participantId, 'profile');
  var newSalt = randomSalt();
  return deriveWrappingKey(pin, newSalt, PBKDF2_ITERATIONS).then(function (wrappingKey) {
    return wrapDataKey(dataKey, wrappingKey);
  }).then(function (wrapped) {
    return readPlain(key).then(function (profile) {
      profile.pin_salt = toBase64(newSalt);
      profile.pin_iterations = PBKDF2_ITERATIONS;
      profile.wrapped_key_iv = wrapped.iv;
      profile.wrapped_key_ciphertext = wrapped.wrapped;
      return writePlain(key, profile);
    });
  });
}

// ----- device key: what lets the app resume with no PIN prompt -----
//
// A second, independent wrapping of the same data key, this time under a non-extractable key
// the browser holds for the page rather than one derived from anything the participant typed.
// It is what tryAutoResume unwraps on a later boot, with no PIN and no network call. See
// crypto.js's generateDeviceKey for what that non-extractability does and does not protect.

// device_key is not encrypted content like history/queue/cachedConfig -- it holds the
// CryptoKey object itself, which storage.js's putRecord clones natively (see that file's
// comment) and which nothing needs a PIN to read, because it can only ever be *used*, never
// exported, by whatever code holds a reference to it.
function readDeviceKey(studyId, participantId) {
  return readPlain(collectionKey(studyId, participantId, 'device_key'));
}
function writeDeviceKey(studyId, participantId, key) {
  return writePlain(collectionKey(studyId, participantId, 'device_key'), key);
}

// Wraps a fresh copy of the data key under a new, non-extractable device key, and stores the
// device token alongside it -- encrypted under that same key when probeCryptoKeyStorage says
// this browser can be trusted with one, or in the clear otherwise (architecture.md section 5.6's
// fallback). Which of the two applies is recorded in the profile, so tryAutoResume never has to
// guess which field to read.
//
// Called once per sign-in event -- createLocalProfile, unlockWithPin, and changePin -- always
// with a token the caller just received from setPin or verifyPin, never minted here. Overwrites
// whatever device key and wrapped copy were on file, which is correct: a fresh sign-in means the
// server has already handed out a new token, and the old device-wrapped copy would only unwrap
// the token that token replaced.
function establishDeviceSession_(studyId, participantId, dataKey, deviceToken) {
  var profileKey = collectionKey(studyId, participantId, 'profile');
  var deviceKey, canStoreKey;
  return probeCryptoKeyStorage().then(function (result) {
    canStoreKey = result;
    return generateDeviceKey();
  }).then(function (key) {
    deviceKey = key;
    return writeDeviceKey(studyId, participantId, deviceKey);
  }).then(function () {
    return wrapDataKey(dataKey, deviceKey);
  }).then(function (wrappedForDevice) {
    var tokenPromise = canStoreKey
      ? encryptJSON(deviceKey, deviceToken).then(function (enc) { return { storage: 'encrypted', enc: enc }; })
      : Promise.resolve({ storage: 'plain', enc: null });
    return tokenPromise.then(function (tokenResult) {
      return readPlain(profileKey).then(function (profile) {
        profile.wrapped_key_device_iv = wrappedForDevice.iv;
        profile.wrapped_key_device_ciphertext = wrappedForDevice.wrapped;
        profile.device_token_storage = tokenResult.storage;
        if (tokenResult.storage === 'encrypted') {
          profile.device_token_enc = tokenResult.enc;
          delete profile.device_token_plain;
        } else {
          profile.device_token_plain = deviceToken;
          delete profile.device_token_enc;
        }
        profile.last_verified_utc = new Date().toISOString();
        return writePlain(profileKey, profile);
      });
    });
  });
}

// Reads the device key and unwraps the data key and the device token, with no PIN and no
// network call. Shows no screen and never throws: any failure along the way (no device key
// stored yet, an unwrap rejected, a corrupted record) simply means there is nothing to resume,
// and the login screen is the correct fallback either way.
//
// @return {Promise<boolean>} True if the session is now unlocked.
function tryAutoResume(studyId, participantId) {
  return getProfile(studyId, participantId).then(function (profile) {
    if (!profile || !profile.wrapped_key_device_iv) return false;
    return readDeviceKey(studyId, participantId).then(function (deviceKey) {
      if (!deviceKey) return false;
      return unwrapDataKey(
        { iv: profile.wrapped_key_device_iv, wrapped: profile.wrapped_key_device_ciphertext }, deviceKey
      ).then(function (dataKey) {
        var tokenPromise = profile.device_token_storage === 'encrypted'
          ? decryptJSON(deviceKey, profile.device_token_enc)
          : Promise.resolve(profile.device_token_plain);
        return tokenPromise.then(function (token) {
          if (!token) return false;
          session = { studyId: studyId, participantId: participantId, tz: profile.tz,
            dataKey: dataKey, deviceToken: String(token) };
          return true;
        });
      });
    });
  }).catch(function () {
    return false;
  });
}

// Records that the server just confirmed this device is still recognised, so a boot long after
// the last successful check can tell a revalidation is overdue (auth.js's
// SESSION_REVALIDATE_DAYS) instead of only ever finding out from a rejected write. Requires an
// active session; a no-op otherwise.
function markSessionVerified() {
  if (!session) return Promise.resolve();
  var key = collectionKey(session.studyId, session.participantId, 'profile');
  return readPlain(key).then(function (profile) {
    if (!profile) return;
    profile.last_verified_utc = new Date().toISOString();
    return writePlain(key, profile);
  });
}

// Changes the PIN. Online-only: setPin is a google.script.run round trip, and queueing a PIN
// change would race against queued markers/surveys sent under the old or new token. Requires an
// active session -- the already-unwrapped session.dataKey is simply re-wrapped under a key
// derived from newPin, with a fresh salt; the server call above is what actually verifies
// oldPin, so nothing here needs to re-derive or re-unwrap with it. The fresh token setPin
// returns is stored the same way a sign-in stores one, so the device stays signed in and the
// new PIN is never retyped.
function changePin(oldPin, newPin) {
  if (!session) return Promise.resolve({ ok: false, reason: 'locked' });
  var studyId = session.studyId, participantId = session.participantId, dataKey = session.dataKey;
  return new Promise(function (resolve) {
    setPin(studyId, participantId, newPin, oldPin,
      function (res) { resolve(res || { ok: false, reason: 'offline' }); },
      function () { resolve({ ok: false, reason: 'offline' }); });
  }).then(function (result) {
    if (!result.ok) return result;
    var key = collectionKey(studyId, participantId, 'profile');
    var newSalt = randomSalt();
    return deriveWrappingKey(newPin, newSalt, PBKDF2_ITERATIONS).then(function (wrappingKey) {
      return wrapDataKey(dataKey, wrappingKey);
    }).then(function (wrapped) {
      return readPlain(key).then(function (profile) {
        profile.pin_salt = toBase64(newSalt);
        profile.pin_iterations = PBKDF2_ITERATIONS;
        profile.wrapped_key_iv = wrapped.iv;
        profile.wrapped_key_ciphertext = wrapped.wrapped;
        profile.pin_set_at = new Date().toISOString();
        return writePlain(key, profile);
      });
    }).then(function () {
      return establishDeviceSession_(studyId, participantId, dataKey, result.deviceToken);
    }).then(function () {
      session.deviceToken = String(result.deviceToken);
      return { ok: true };
    });
  });
}

// Ends the session: best-effort tells the server to forget this device's token, then deletes
// the device key, the device-wrapped copy of the data key, and the stored token -- the PIN-
// wrapped copy, history, queue, and cached config are all untouched, so logging back in with the
// correct PIN sees the same history again. See docs/architecture.md's local storage section.
//
// Used both for an explicit "Log out" and for the softer case in auth.js where the server no
// longer recognises this device's token: either way, the point is that the next boot must not
// silently auto-resume with material the server has already stopped honoring.
function logout(studyId, participantId) {
  var token = session ? session.deviceToken : null;
  session = null;
  var signOut = token
    ? new Promise(function (resolve) {
        signOutDevice(studyId, participantId, token, function () { resolve(); }, function () { resolve(); });
      })
    : Promise.resolve();
  return signOut.then(function () {
    return deleteRecord(collectionKey(studyId, participantId, 'device_key'));
  }).then(function () {
    var key = collectionKey(studyId, participantId, 'profile');
    return readPlain(key).then(function (profile) {
      if (!profile) return;
      delete profile.wrapped_key_device_iv;
      delete profile.wrapped_key_device_ciphertext;
      delete profile.device_token_storage;
      delete profile.device_token_enc;
      delete profile.device_token_plain;
      return writePlain(key, profile);
    });
  });
}

// Deletes every namespaced record for one identity, including its device key. Destructive, and
// not wired to any button in Phase 3 -- kept for completeness, not as a "forget this device"
// feature nobody has asked for.
function wipeProfile(studyId, participantId) {
  return Promise.all(['profile', 'history', 'surveys', 'queue', 'cachedConfig', 'device_key'].map(function (name) {
    return deleteRecord(collectionKey(studyId, participantId, name));
  }));
}

function getSessionToken() {
  return session ? session.deviceToken : null;
}
function getSessionIdentity() {
  return session ? { studyId: session.studyId, participantId: session.participantId, tz: session.tz } : null;
}

// ----- content collections (require an active session) -----

function getHistory() {
  if (!session) return Promise.reject(new Error('locked'));
  return readEncrypted(session.dataKey, collectionKey(session.studyId, session.participantId, 'history'), []);
}
function setHistory(arr) {
  return updateHistory(function () { return arr; });
}
function updateHistory(mutatorFn) {
  return updateCollection('history', mutatorFn, []);
}

function getQueue() {
  if (!session) return Promise.reject(new Error('locked'));
  return readEncrypted(session.dataKey, collectionKey(session.studyId, session.participantId, 'queue'), []);
}
function setQueue(arr) {
  return updateQueue(function () { return arr; });
}
function updateQueue(mutatorFn) {
  return updateCollection('queue', mutatorFn, []);
}

// Local record of every survey this device knows about, keyed within the array by survey_id --
// not by night, because a night can outlive several attempts (skipped, then completed later)
// under the same survey_id. This is what lets history.js and survey.js tell "skipped, still
// completable" apart from "submitted, locked" without asking the server, and what the
// completion flow reads to decide whether it is starting fresh or resuming a draft.
function getSurveys() {
  if (!session) return Promise.reject(new Error('locked'));
  return readEncrypted(session.dataKey, collectionKey(session.studyId, session.participantId, 'surveys'), []);
}
function setSurveys(arr) {
  return updateSurveys(function () { return arr; });
}
function updateSurveys(mutatorFn) {
  return updateCollection('surveys', mutatorFn, []);
}

// Cached copy of getConfig()'s last successful result (edit window + question list), read
// before ever falling back to the generic hardcoded defaults, so a participant opening the app
// offline days after their last successful fetch still sees their study's actual questions.
function getCachedConfig() {
  if (!session) return Promise.reject(new Error('locked'));
  return readEncrypted(session.dataKey, collectionKey(session.studyId, session.participantId, 'cachedConfig'), null);
}
function setCachedConfig(cfg) {
  return updateCollection('cachedConfig', function () { return cfg; }, null);
}

var editWindowDays = 7; // fallback until server config loads (see loadConfig)

// Editable if this specific event's own logged time is within the edit window.
function isEditable(ev) {
  if (!ev) return false;
  var ageDays = (Date.now() - Number(ev.event_epoch_ms)) / 86400000;
  return ageDays <= editWindowDays;
}

// Mirrors the server's daysSinceSleepDay_: whole calendar days between a sleep_day and today,
// with no time-of-day component -- a survey is measured by the night it describes, not by an
// instant, the same "measured from the stored value" principle isEditable applies to markers.
// Lets the history screen hide a completion entry point before ever asking the server, using the
// same day count logSurvey's own guard enforces.
function isSleepDayCompletable(sleepDay) {
  var s = String(sleepDay).split('-').map(Number);
  var sleepDayUtc = Date.UTC(s[0], s[1] - 1, s[2]);
  var t = new Date().toISOString().slice(0, 10).split('-').map(Number);
  var todayUtc = Date.UTC(t[0], t[1] - 1, t[2]);
  var ageDays = Math.round((todayUtc - sleepDayUtc) / 86400000);
  return ageDays <= editWindowDays;
}

var APP_VERSION = '1.0.0';

function uuid() {
  if (window.crypto && crypto.randomUUID) return crypto.randomUUID();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    var r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// identity is a plain {study_id, participant_id, tz} object, not the vault's own in-memory
// session -- kept distinctly named so the two are never confused once every src/data and
// src/logic file is concatenated into one script scope by build.py.
//
// Field names (marker, event_utc, event_local, event_tz) match logMarker's payload exactly, so
// marker-payload.js can pass this object straight through with only the credential added.
function buildEvent(marker, identity, epochMs) {
  var ms = epochMs || Date.now();
  return {
    record_id: uuid(),
    study_id: identity.study_id,
    participant_id: identity.participant_id,
    marker: marker,
    event_epoch_ms: ms, // local-only convenience for sorting/pairing; never sent to the server
    event_utc: new Date(ms).toISOString(),
    event_tz: identity.tz,
    event_local: toLocalIsoWithOffset(ms, identity.tz),
    app_version: APP_VERSION
  };
}

// Matches logMarker's payload exactly (src/server/Code.gs). study_id/participant_id come from
// the event itself rather than the session, so a queued marker still sends the identity it was
// recorded under even if the session has since changed.
function toLogMarkerPayload(event) {
  return {
    study_id: event.study_id,
    participant_id: event.participant_id,
    device_token: getSessionToken(),
    record_id: event.record_id,
    marker: event.marker,
    event_local: event.event_local,
    event_tz: event.event_tz,
    event_utc: event.event_utc,
    source: 'web',
    app_version: APP_VERSION
  };
}

// Matches updateMarker's payload. client_edit_utc is the instant the edit was made on the
// device, not when it happens to reach the server -- an edit made inside the edit window but
// queued offline is judged by when it was made, per section 10 of the architecture
// specification, so this has to be captured once, at edit time, and carried with the queued item
// rather than recomputed when the queue finally drains.
function toUpdateMarkerPayload(editedEvent, clientEditUtc) {
  return {
    study_id: editedEvent.study_id,
    participant_id: editedEvent.participant_id,
    device_token: getSessionToken(),
    record_id: editedEvent.record_id,
    event_local: editedEvent.event_local,
    event_tz: editedEvent.event_tz,
    event_utc: editedEvent.event_utc,
    client_edit_utc: clientEditUtc,
    source: 'web',
    app_version: APP_VERSION
  };
}

// Walks local history oldest-first, closing each SLEEP with the next WAKE it meets. A SLEEP with
// no WAKE yet (still asleep, or the pair was interrupted) surfaces with wake: null; a WAKE with
// no preceding SLEEP (the very first entry on a device, or a missed tap) surfaces with
// sleep: null. Returned newest-first, matching how the history screen lists nights.
function pairNights(events) {
  var asc = events.slice().sort(function (a, b) { return a.event_epoch_ms - b.event_epoch_ms; });
  var nights = [];
  var openSleep = null;
  asc.forEach(function (e) {
    if (e.marker === 'SLEEP') {
      if (openSleep) nights.push({ sleep: openSleep, wake: null });
      openSleep = e;
    } else {
      nights.push({ sleep: openSleep, wake: e });
      openSleep = null;
    }
  });
  if (openSleep) nights.push({ sleep: openSleep, wake: null });
  return nights.reverse();
}

// Mirrors sleepDayFromWallClock_ exactly: a night starting before noon local time belongs to the
// previous calendar day. Takes plain wall-clock components rather than a Date built in the
// browser's own zone, so a participant traveling away from their study time zone still gets the
// date that belongs to the clock they read, not the date the device happens to be sitting in.
function sleepDayFromWallClock(year, month, day, hour) {
  var d = new Date(Date.UTC(year, month - 1, day));
  if (hour < 12) d.setUTCDate(d.getUTCDate() - 1);
  return d.toISOString().slice(0, 10);
}

// The inverse of sleepDayFromWallClock: given a night and a clock time on it, which calendar
// date does that clock time fall on? A time before noon belongs to the morning after the night
// started; noon onward belongs to the same evening, per architecture.md section 4.1.
function dateForClockOnSleepDay(sleepDay, hour) {
  var s = String(sleepDay).split('-').map(Number);
  var d = new Date(Date.UTC(s[0], s[1] - 1, s[2]));
  if (hour < 12) d.setUTCDate(d.getUTCDate() + 1);
  return d.toISOString().slice(0, 10);
}

// A survey's `time` question only asks for a clock reading (architecture.md section 3.4); the
// calendar date is derived from the night being described, via dateForClockOnSleepDay, then
// combined with the participant's time zone into the stored local-ISO-with-offset form.
function localIsoForTimeAnswer(sleepDay, hhmm, tz) {
  var m = /^(\d{2}):(\d{2})/.exec(String(hhmm || ''));
  if (!m) return null;
  var hour = Number(m[1]), minute = Number(m[2]);
  var dateStr = dateForClockOnSleepDay(sleepDay, hour);
  var d = dateStr.split('-').map(Number);
  return toLocalIsoWithOffset(epochFromWallTime(d[0], d[1], d[2], hour, minute, tz), tz);
}

// A survey's `datetime` question asks for the date directly, so no sleep_day derivation applies.
function localIsoForDatetimeAnswer(dateStr, hhmm, tz) {
  var d = String(dateStr).split('-').map(Number);
  var m = /^(\d{2}):(\d{2})/.exec(String(hhmm || ''));
  if (!m) return null;
  return toLocalIsoWithOffset(epochFromWallTime(d[0], d[1], d[2], Number(m[1]), Number(m[2]), tz), tz);
}

// Reads the date and hour straight out of a local ISO string (as toLocalIsoWithOffset produces,
// or as the datetime-local edit field's "YYYY-MM-DDTHH:mm" value already is) without ever
// constructing a browser-local Date from it, which would reinterpret the wall-clock numbers
// through whatever zone the device itself is in.
function sleepDayFromLocal(localIso) {
  var m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/.exec(String(localIso || ''));
  if (!m) return null;
  return sleepDayFromWallClock(Number(m[1]), Number(m[2]), Number(m[3]), Number(m[4]));
}

// Mirrors findPrecedingSleepDay_: the sleep_day a WAKE at or after beforeEpochMs should carry is
// the most recent SLEEP's own sleep_day, or -- if this device holds no SLEEP before it at all --
// the noon rule applied to the WAKE's own local time.
//
// @param {Array<Object>} events Local history entries, each carrying marker, event_epoch_ms,
//     and event_local. Order does not matter; every SLEEP is considered.
// @param {number} beforeEpochMs The WAKE's own instant. A SLEEP at or before this counts.
// @param {string} fallbackLocalIso The WAKE's own event_local, used only if no SLEEP qualifies.
// @return {?string} 'YYYY-MM-DD', or null if fallbackLocalIso cannot be parsed either.
function findPrecedingSleepDayLocal(events, beforeEpochMs, fallbackLocalIso) {
  var mostRecent = null;
  (events || []).forEach(function (e) {
    if (!e || e.marker !== 'SLEEP' || e.event_epoch_ms > beforeEpochMs) return;
    if (!mostRecent || e.event_epoch_ms > mostRecent.event_epoch_ms) mostRecent = e;
  });
  return mostRecent ? sleepDayFromLocal(mostRecent.event_local) : sleepDayFromLocal(fallbackLocalIso);
}

function fmtClock(epochMs, tz) {
  return new Date(epochMs).toLocaleTimeString('en-US',
    { timeZone: tz, hour: 'numeric', minute: '2-digit' });
}
function sameDay(epochMs, tz) {
  var opt = { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit' };
  return new Date(epochMs).toLocaleDateString('en-US', opt) ===
         new Date().toLocaleDateString('en-US', opt);
}
function fmtTime(ev) { return ev ? fmtClock(ev.event_epoch_ms, ev.event_tz) : '--'; }
function fmtDate(ev) {
  return new Date(ev.event_epoch_ms).toLocaleDateString('en-US',
    { timeZone: ev.event_tz, weekday: 'short', month: 'short', day: 'numeric' });
}
function fmtDur(ms) {
  var m = Math.round(ms / 60000), h = Math.floor(m / 60);
  return h + 'h ' + (m % 60) + 'm';
}

// Format an instant as "YYYY-MM-DDTHH:mm" in the given IANA tz, for a datetime-local input.
function toDatetimeLocalValue(epochMs, tz) {
  var dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: tz, hourCycle: 'h23',
    year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit'
  });
  var p = dtf.formatToParts(new Date(epochMs)).reduce(function (acc, x) { acc[x.type] = x.value; return acc; }, {});
  return p.year + '-' + p.month + '-' + p.day + 'T' + p.hour + ':' + p.minute;
}

// How far the wall clock in tz differs from UTC at this instant (ms), via Intl (no tz library).
function tzOffsetMs(date, tz) {
  var dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: tz, hourCycle: 'h23',
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit'
  });
  var p = dtf.formatToParts(date).reduce(function (acc, x) { acc[x.type] = x.value; return acc; }, {});
  var asUtc = Date.UTC(Number(p.year), Number(p.month) - 1, Number(p.day), Number(p.hour), Number(p.minute), Number(p.second));
  return asUtc - date.getTime();
}

// Wall-clock date/time components as read in tz -> epoch ms. Two passes to settle across DST edges.
function epochFromWallTime(y, mo, d, h, mi, tz) {
  var guess = Date.UTC(y, mo - 1, d, h, mi, 0);
  var offset = tzOffsetMs(new Date(guess), tz);
  var epoch = guess - offset;
  offset = tzOffsetMs(new Date(epoch), tz);
  return guess - offset;
}

function pad2(n) { return (n < 10 ? '0' : '') + n; }

// Format an instant as "YYYY-MM-DDTHH:mm:ss±HH:mm" in the given IANA tz -- the local-time-with-
// offset form architecture.md section 4.1 requires for every stored clock time (markers and
// survey answers alike). Built from the same Intl parts and tzOffsetMs that
// toDatetimeLocalValue and epochFromWallTime already use, so all three stay consistent with
// each other.
function toLocalIsoWithOffset(epochMs, tz) {
  var date = new Date(epochMs);
  var dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: tz, hourCycle: 'h23',
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit'
  });
  var p = dtf.formatToParts(date).reduce(function (acc, x) { acc[x.type] = x.value; return acc; }, {});
  var offsetMinutes = Math.round(tzOffsetMs(date, tz) / 60000);
  var sign = offsetMinutes < 0 ? '-' : '+';
  var abs = Math.abs(offsetMinutes);
  return p.year + '-' + p.month + '-' + p.day + 'T' + p.hour + ':' + p.minute + ':' + p.second +
    sign + pad2(Math.floor(abs / 60)) + ':' + pad2(abs % 60);
}
