// This file is part of MiNap Go
// core.js
// Author(s): Gabriel Mongefranco
// Created: 2026-08-18
// Last Modified: 2026-08-18
// Summary: Storage and domain-rule logic for the MiNap Go client, merged from src/data/ and src/logic/.
// Notes: See README file for documentation and full license information.
// Generated by build.py from src/data/, src/logic/. Do not edit directly; edit the source and rerun build.py.
//
// Copyright © 2026 The Regents of the University of Michigan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along
// with this program. If not, see <https://www.gnu.org/licenses/>.

var K_SESSION = 'minap.session';
var K_HISTORY = 'minap.history';
var K_QUEUE = 'minap.queue';

function load(key, fallback) {
  try { var v = localStorage.getItem(key); return v ? JSON.parse(v) : fallback; }
  catch (e) { return fallback; }
}
function save(key, val) {
  try { localStorage.setItem(key, JSON.stringify(val)); } catch (e) {}
}
function clearAll() {
  [K_SESSION, K_HISTORY, K_QUEUE].forEach(function (k) {
    try { localStorage.removeItem(k); } catch (e) {}
  });
}

var editWindowDays = 7; // fallback until server config loads (see loadConfig)

// Editable if this specific event's own logged time is within the edit window.
function isEditable(ev) {
  if (!ev) return false;
  var ageDays = (Date.now() - Number(ev.event_epoch_ms)) / 86400000;
  return ageDays <= editWindowDays;
}

var APP_VERSION = '1.0.0';

function uuid() {
  if (window.crypto && crypto.randomUUID) return crypto.randomUUID();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    var r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

function buildEvent(type, session, epochMs) {
  var ms = epochMs || Date.now();
  var d = new Date(ms);
  return {
    record_id: uuid(),
    study_id: session.study_id,
    participant_id: session.participant_id,
    event_type: type,
    event_epoch_ms: ms,
    event_iso_utc: d.toISOString(),
    event_tz: session.tz,
    event_local: d.toLocaleString('en-US', { timeZone: session.tz, hour12: true }),
    app_version: APP_VERSION
  };
}

function fmtClock(epochMs, tz) {
  return new Date(epochMs).toLocaleTimeString('en-US',
    { timeZone: tz, hour: 'numeric', minute: '2-digit' });
}
function sameDay(epochMs, tz) {
  var opt = { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit' };
  return new Date(epochMs).toLocaleDateString('en-US', opt) ===
         new Date().toLocaleDateString('en-US', opt);
}
function fmtTime(ev) { return ev ? fmtClock(ev.event_epoch_ms, ev.event_tz) : '--'; }
function fmtDate(ev) {
  return new Date(ev.event_epoch_ms).toLocaleDateString('en-US',
    { timeZone: ev.event_tz, weekday: 'short', month: 'short', day: 'numeric' });
}
function fmtDur(ms) {
  var m = Math.round(ms / 60000), h = Math.floor(m / 60);
  return h + 'h ' + (m % 60) + 'm';
}

// Format an instant as "YYYY-MM-DDTHH:mm" in the given IANA tz, for a datetime-local input.
function toDatetimeLocalValue(epochMs, tz) {
  var dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: tz, hourCycle: 'h23',
    year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit'
  });
  var p = dtf.formatToParts(new Date(epochMs)).reduce(function (acc, x) { acc[x.type] = x.value; return acc; }, {});
  return p.year + '-' + p.month + '-' + p.day + 'T' + p.hour + ':' + p.minute;
}

// How far the wall clock in tz differs from UTC at this instant (ms), via Intl (no tz library).
function tzOffsetMs(date, tz) {
  var dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: tz, hourCycle: 'h23',
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit'
  });
  var p = dtf.formatToParts(date).reduce(function (acc, x) { acc[x.type] = x.value; return acc; }, {});
  var asUtc = Date.UTC(Number(p.year), Number(p.month) - 1, Number(p.day), Number(p.hour), Number(p.minute), Number(p.second));
  return asUtc - date.getTime();
}

// Wall-clock date/time components as read in tz -> epoch ms. Two passes to settle across DST edges.
function epochFromWallTime(y, mo, d, h, mi, tz) {
  var guess = Date.UTC(y, mo - 1, d, h, mi, 0);
  var offset = tzOffsetMs(new Date(guess), tz);
  var epoch = guess - offset;
  offset = tzOffsetMs(new Date(epoch), tz);
  return guess - offset;
}
