// This file is part of MiNap Go
// sw.js
// Author(s): Gabriel Mongefranco
// Created: 2026-08-18
// Last Modified: 2026-08-18
// Summary: Service worker placeholder for the standalone build. Not registered by app/index.html yet.
// Notes: See README file for documentation and full license information.
// Generated by build.py from build_service_worker() in build.py (no single src/ file backs this one). Do not edit directly; edit the source and rerun build.py.
//
// Copyright © 2026 The Regents of the University of Michigan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along
// with this program. If not, see <https://www.gnu.org/licenses/>.
// Intentionally inert: no caching logic, and nothing in app/ registers this worker
// yet. Kept as its own file because a service worker's scope is fixed to the URL
// it is served from, so it cannot be merged with another script.
